### ISSUE TITLE
Conditional Schema

### ISSUE THREAD

**Issue by jacobstr** [pyeve/cerberus#136]
Suppose I want to support an abstract payload that uses another field to drive nested validations:

```
TEST_TASK = {
    "folder": {
        "required": True
    }
}

BUILD_TASK = {
    "environment": {
        "allowed": ["staging", "product"]
    }
}

ABSTRACT_TASK = {
    'type': {
        'allowed': ['test', 'build']
    },
    'data': {
        'type': 'dict',
        'required': True,
        'anyof': [
            {'schema': TEST_TASK},
            {'schema': BUILD_TASK}
        ]
    }
}

>>> validator = cerberus.Validator(schemas.ABSTRACT_TASK)
>>> validator.validate({
    "type": "build",
    "data": {
        "environment": "bad"
    }
})
>>> pp validator.errors
{'data': {'anyof': 'no definitions validated',
      'definition 0': {'environment': 'unknown field',
                       'folder': 'required field'},
      'definition 1': {'environment': 'unallowed value bad'}}}
```

Is there a way to conditionally use `definition  1` when the parent has a type of `build`? For example, if the ABSTRACT_TASK is modified so that `anyof` is replaced with the BUILD_TASK schema:

```
>>> pp validator.errors
{'data': {'environment': 'unallowed value bad'}}
```

**Comment by funkyfuture** [comment]
nope, not straight-forward,

you could write a custom validator that checks either `TEST_TASK` or `BUILD_TASK` depending on what it figures out from `self.root_document`.

if you come up with something that can be generalised and get simply defined in a `dict` you're welcome to contribute.

another way to tackle this would be not to abstract, but to make `TEST_`-and `BUILD_TASK` top-level objects and mixin definitions.

**Comment by funkyfuture** [comment]
some quick thought regarding a rule for this use-case. if a `Validator`-instance had a `trail`-property as proposed in #93, it should be easy to implement something like dependencies that relate to parent-objects.

(i will do some stuff on cerberus this weekend anyway, i'll see that i get a `trail` in.)

**Comment by funkyfuture** [comment]
what about such constructs?

    {'if': {rule: constraint, …}, 'then': {rule: constraint, …}, 'else': {rule: constraint, …}}

**Comment by funkyfuture** [comment]
or?

    field: {'case': {condition_schema1: conditional_schema1}, {'condition_schema2: conditional_schema2}}

**Comment by funkyfuture** [comment]
i documented the inital question on [SO](https://stackoverflow.com/questions/46620028). regarding the conditional validation, i have a better idea for the future. imo, this issue can be closed.
