### ISSUE TITLE
Range restrictions for dependency values

### ISSUE THREAD

**Issue by adityaramesh** [pyeve/cerberus#182]
It would be useful to be able to make a field required if and only if the value of some other integral field falls within a specific range. To my knowledge, this can't be done very easily as things are. A specific case of this is the positivity constraint. For numeric quantities, the value zero is a more canonical way to indicate the lack of something than `None`. For example, if a document corresponds to some sort of computing resource, then it may make sense for another field to be defined if and only if another field (say, memory requested or consumed) is positive.

**Comment by funkyfuture** [comment]
have you considered to use altering rules with the `oneof`-rule?

**Comment by adityaramesh** [comment]
I'm not quite sure I userstand. Do you mean explicitly specifying each allowable positive value in a list using one-of?

**Comment by funkyfuture** [comment]
no, i mean to define different excluding schemas where each describes a valid context and only one can be valid at a time.

**Comment by funkyfuture** [comment]
is this issue solved?

**Comment by funkyfuture** [comment]
i think this can be closed, it's similar to #136.
