### ISSUE TITLE
All fields can be empty but at least one set in  a dict

### ISSUE THREAD

**Issue by botzill** [pyeve/cerberus#221]
Hi guys. 

I have a scenario and not sure how can I easily achieve this, use existing helpers or write my own validator for this.

I have a simple dict like:

``` json
{
  "a_dict": {
    "field1": "test1",
    "field2": "test2",
    "field3": "test3",
  }
}
```

now, any field can be empty, but at least one should be set. How can I achieve this, is there any already implemented way or I should write my own validator? Here is my schema:

``` python
"a_dict": {
            "type": "dict",
            "schema": {
                "field1": {
                    "type": "string",
                    "required": False
                },
                "field2": {
                    "type": "string",
                    "required": False
                },
                "field3": {
                    "type": "string",
                    "required": False
                },
            }
        }
```

Thx.

**Comment by laoyur** [comment]
Hi, I have a same requirement, could someone helps ?

**Comment by funkyfuture** [comment]
this should do it:

```python
'a_dict': {'type': 'dict',
           'minlength': 1}
```

if the field's names are of relevance, have a look at the `anyof` rule, in particular `anyof_schema`.

contributions with regard to #229 are welcome.

**Comment by funkyfuture** [comment]
i've addressed the question on [SO](https://stackoverflow.com/q/46620377/2489914), so this issue can be closed.
