### ISSUE TITLE
extend documentation with advanced usages

### ISSUE THREAD

**Issue by funkyfuture** [pyeve/cerberus#229]
there are repeated requests for support with special use cases. mostly these are solvable with one of the `*of`-rules. currently open issues are #221, #194, #182 and #136.

it seems advisable to add a page to the docs that covers more complex uses of cerberus by examples. beside the fact that i'm not really keen on solving other people's detailed problems, it also seems advisable that these examples are written from a user's perspective. but certainly i'm willing to support this by giving hints and reviewing.

has anyone an idea how to encourage people to share their experiences and solutions?

**Comment by nicolaiarocci** [comment]
Would also be a great occasion for people to contribute to an open source project. In Eve we have a [Snippets](http://python-eve.org/snippets/) section which is supposed to receive user snippets and use cases. Maybe something like this would work? Can't say it got a lot of traction in Eve.

**Comment by funkyfuture** [comment]
it's not the case that i don't have strong arguments against the following proposal, but i tend to close this issue and outsource any support questions to StackOverflow.
