### ISSUE TITLE
Interest for a purge_readonly flag?

### ISSUE THREAD

**Issue by yohanboniface** [pyeve/cerberus#240]
My use case is that I have some fields that I want to expose, but are not writable in POST/PUT/PATCH.
Instead of raising when someone pass one of them, I'd prefer to remove it from the document.
I can do that on my side, but if there is interest I can instead provide a pull request.

**Comment by nicolaiarocci** [comment]
How would you implement that? A new `purge` rule maybe?

**Comment by funkyfuture** [comment]
certainly, conditional normalization in general is of interest. some people already tried to make use of the anyof-rule to achieve that. in any case it requires major refactoring which is why I'd propose it for a post 1.0 release.

before discussing implementation options, I think it's a good idea to collect further use cases and discuss syntax proposals.

can you solve your need with a custom validator atm?

**Comment by yohanboniface** [comment]
> can you solve your need with a custom validator atm?

Yep, I've a custom one anyway.
My question was more about the interest of pushing that upstream.

And my idea was to implement a global flag `purge_readonly`, just like we have a `purge_unknown`.

I'll keep an eye on the thread to see if a preferred implementation raises up.

**Comment by drcraig** [comment]
I have the exact same usecase as @yohanboniface, and actually initially thought that's what `readonly` was for, but thought I was doing something wrong.

**Comment by funkyfuture** [comment]
for the sake of simplicity and from what i can conceptualize as use-case, i propose to make that an instance configuration like `purge_unknown` and not a rule. and that this gets assigned to the 1.3 milestone. is that allright for everyone?

**Comment by funkyfuture** [comment]
there's one thing not to forget: the order in which the various normalization rules are applied matters. with the growing amount of possible alterations there's no way around the capability to configure that order per validator instance (and for some that might not be granular enough).

**Comment by funkyfuture** [comment]
@yohanboniface, in your initial post you mention a pr. do you have some code that can be integrated into Cerberus?

**Comment by yohanboniface** [comment]
Nope, sorry :(
