### ISSUE TITLE
[Feature Request] Rename all fields

### ISSUE THREAD

**Issue by AlJohri** [pyeve/cerberus#261]
I was wondering if its possible to rename all fields based on a rule (method)? My use case is to be able to take camel case json input and automatically convert to PEP 8 style snake case. I can then run my validations on the data all written using snake case variable names.

**Comment by funkyfuture** [comment]
yup, there's the rename_handler rule.

**Comment by funkyfuture** [comment]
i'm not sure whether this is possible:

```python
schema = {}
allow_unknown = {'rename_handler': camel_to_snail}
document = {'JavaSucks`: ...}
document = validator.normalized(document, schema, allow_unknown=allow_unknown)
```

if not, please report back.

**Comment by funkyfuture** [comment]
this issue can be closed, right?
