### ISSUE TITLE
Custom error message with 1.0

### ISSUE THREAD

**Issue by yohanboniface** [pyeve/cerberus#262]
Following https://github.com/nicolaiarocci/cerberus/commit/cd25750d017aa899f7a99b20a75af9260a790b6f#commitcomment-18949472

Upgrading from 0.9 to 1.0, I wonder how I can have custom error messages in _validate_xxx methods.
Here is what I've with 0.9 version for example:

```
def _validate_type_foreignkey(self, field, value):
    if not isinstance(value, int):
        self._error(field, 'No matching resource for {}'.format(value))
```

I see that in 1.0 _validate_xxx methods should only return a boolean according to the validation status, but then I'm not sure how I can have a custom error message when some field does not validate.

Thanks for your lights.

**Comment by funkyfuture** [comment]
in 1.0 validation methods and error representation are segregated concerns.

having that said, i want to boint you to the `errors.BasicErrorHandler`, in particular the method `format_message`.

is that `__call__` thing still an issue?

**Comment by shivekkhurana** [comment]
Hi @funkyfuture 

Thanks for this amazing library, it has saved me tons of work.

I want to achieve the following behaviour, 
```python
def _validate_type_objectid(self, field, value):
    """ Enables validation for `objectid` schema attribute.

    :param field: field name.
    :param value: field value.
    """
    if not re.match('[a-f0-9]{24}', value):
        self._error(field, ERROR_BAD_TYPE.format('ObjectId'))
```

But am stuck at the `validator._validate_type` function :
```python
    def _validate_type(self, data_type, field, value):
        """ {'type': ['string', 'list']} """
        types = [data_type] if isinstance(data_type, _str_type) else data_type
        if not any(self.__get_rule_handler('validate_type', x)(value)
                   for x in types):
            self._error(field, errors.BAD_TYPE)
            self._drop_remaining_rules()
```

**And am not able to understand how to alter this behaviour and send a custom error message instead.** I wasn't able to make anything from errors.BasicErrorHandler either.

I understand that separation of validation and error representation are two separate concerns, but how to achieve the desired behaviour in that case ? 

Thanks & Regards

**Comment by shivekkhurana** [comment]
(I'm using Cerberus==1.1 with python2.7)

**Comment by funkyfuture** [comment]
@shivekkhurana , you should not misuse the 'type' rule for tests that are not type-related, and instead use 'validator'. see #335.

for further support, please refer to the [API documentation](http://docs.python-cerberus.org/en/stable/api.html#cerberus.Validator._error) and consider asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cerberus).
