### ISSUE TITLE
Nested 'rename' handlers fail normalization

### ISSUE THREAD

**Issue by derek-miller** [pyeve/cerberus#266]
Since normalization works top-down nested `rename` handlers will not work. I discovered this when I was looking into #260.

``` python
>>> import cerberus
>>> validator = cerberus.Validator(schema={'foo': {'type': 'dict', 'schema': {'bar': {'rename': 'baz'}}, 'rename': 'bar'}})
>>> assert validator.normalized({'foo': {'bar': 0}}) == {'bar': {'baz': 0}}
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AssertionError
```

Seem like a big change to get this to work in a bottom up approach.

**Comment by funkyfuture** [comment]
i wouldn't be sure whether this would always be the desired behavior.

you could define the inner renaming for the top-level field `bar`. though in that case the order in which fields are normalized isn't deterministic.

the order in `__normalize_mapping` could also be changed.

**Comment by wilhelmg** [comment]
Is there possibly an estimate on this functionality? Nested 'rename' handlers would be very useful.

**Comment by funkyfuture** [comment]
i think that

a) there's no general solution for this covering all possible scenarios.
b) implementing this would be a lot of pain. (though i'm interested in clean solutions.)
c) a solution would be to allow a [chaining of schemata](https://github.com/pyeve/cerberus/pull/348/files#diff-38574c080d4e2eb38c49b86e6588ad98R82), this way a document would be normalized and validated just with regards to the lop-level objects in this case, and further normalization / validation happens with another schema that relies on the constraints of the previous.

**Comment by funkyfuture** [comment]
this issue can be closed, right?
