### ISSUE TITLE
docs: API reference at python-cerberus.org lacks generated contents

### ISSUE THREAD

**Issue by funkyfuture** [pyeve/cerberus#281]
- I consulted these documentations:
  - [x] http://docs.python-cerberus.org/en/stable/
  - [x] http://docs.python-cerberus.org/en/latest/

- I consulted these sections of the docs:
  - API

- [x] I have the capacity to submit a patch when a bug is identified.

----

#### Bug report

i just noticed that these [generated](https://github.com/nicolaiarocci/cerberus/blob/master/docs/includes/generate.py) includes of the docs do not appear in the online docs while they do in a local build:

http://docs.python-cerberus.org/en/stable/api.html#error-codes
http://docs.python-cerberus.org/en/stable/api.html#schema-validation-schema

**Comment by funkyfuture** [comment]
is the checkbox "Install your project inside a virtualenv using setup.py install" checked in the Advanced Settings of the RtD-project? if not, maybe the call to `docs/includes/generate.py` should be in `conf.py` rather than in the Makefile to let the build fail if there's a problem.

**Comment by nicolaiarocci** [comment]
Yes the checkbox is checked now (it wasn't), but it does not seem to solve the issue.

**Comment by funkyfuture** [comment]
now it also seems to affect [builds](https://travis-ci.org/pyeve/cerberus/jobs/249826748) on travis.

**Comment by funkyfuture** [comment]
maybe a git-hook that updates the then repo-included assets is the most durable solution?

**Comment by nicolaiarocci** [comment]
Seems odd to me that only py35 is affected on travis.

**Comment by funkyfuture** [comment]
that is because the doctests run on it: https://github.com/pyeve/cerberus/blob/master/tox.ini#L36

**Comment by funkyfuture** [comment]
i pledge to mark this for the `1.2` milestone.
