### ISSUE TITLE
yaml validation

### ISSUE THREAD

**Issue by kyrylo-shpytsya-prism** [pyeve/cerberus#293]
I need to validate yaml data, which is loaded using PyYAML or its fork, ruamel.yaml. My goal is to provide the user with exact locations (like line:column) of validation errors.

E.g. given the following input:

> dict:
>> 1: "a"

and the following schema:

> {'dict': {'keyschema': {'type': 'string'},
>           'type': 'dict',
>           'valueschema': {'type': 'integer'}}}
 
instead of mere

> {'dict': [{1: ['must be of string type', 'must be of integer type']}]}

I would like something that would point to both key and value.

My initial approach was to use `yaml.compose`, which for above mentioned data would result in the following structure:

> MappingNode(tag=u'tag:yaml.org,2002:map', value=[(ScalarNode(tag=u'tag:yaml.org,2002:str', value=u'dict'), MappingNode(tag=u'tag:yaml.org,2002:map', value=[(ScalarNode(tag=u'tag:yaml.org,2002:int', value=u'1'), ScalarNode(tag=u'tag:yaml.org,2002:str', value=u'a'))]))])

and process it with `yaml.Loader("").construct_document(root_node)` to obtain plain Python data structure (`{'dict': {1: 'a'}}`) which I would then feed to validator.

Then, in case of validation failure I would need to match errors to the tree produced by `yaml.compose` which contains, for each node, exact location in source text.

And here lies my problem: `validator._errors` seems to be too low-level and `validator.errors` seems to miss the information that would make it possible to differentiate between key and value. My suspicion that a custom `XxxErrorHandler` could do the trick but I would not like to dive too deep into that without being sure that it is indeed possible. 

Also, maybe it would be possible to use [this](https://nicolaiarocci.com/validating-user-objects-cerberus/) approach to validate data produced by `yaml.compose` directly, but I am not that deeply familiar with the architecture to see how to accomplish that.

Please advise.

P.S. As I intend to load schema from yaml as well, it would be nice also not as critical to be able to diagnose errors in the schema itself with the same approach, i.e. provide exact location in the source file.

**Comment by funkyfuture** [comment]
> Then, in case of validation failure I would need to match errors to the tree produced by yaml.compose which contains, for each node, exact location in source text.

if i get this right, you may be looking for the [document_error_tree](http://docs.python-cerberus.org/en/stable/api.html#cerberus.Validator.document_error_tree).

**Comment by kyrylo-shpytsya-prism** [comment]
I fail to see – most probably due to scarce documentation – how `document_error_tree` would allow differentiation between an error in a key and an error in a value. Moreover, it appears that the errors accessed via `document_error_tree` are the low level error objects which do not contain human readable error explanation.
To clarify my initial example, my goal is to be able to output:

2:5: must be of string type
2:8: must be of integer type

I understand that unless it is possible to make cerberus validate yaml nodes directly (instead of pure python structure), I would have to implement "get node by path" to obtain yaml nodes from paths from validation errors. The problem is that path, by itself, does not allow differentiation between key and value.

I do not mind coding, I just would want neither implementing a bicycle nor relying too much on internal representation which may change in the future.

So I guess I am looking for something which would allow enumeration of errors as `(node-path, is-error-in-key, human-readable-error-explanation)` tuples.

**Comment by funkyfuture** [comment]
> I fail to see – most probably due to scarce documentation – how document_error_tree would allow differentiation between an error in a key and an error in a value.

i related that to

>for each node, exact location in source text.

on a `ValidationError` instance (e.g. queried from that tree) you can inspect the [schema_path](http://docs.python-cerberus.org/en/stable/api.html#cerberus.errors.ValidationError.schema_path) whether `keyschema` or `valueschema` are a parent node.

> I do not mind coding, I just would want neither implementing a bicycle nor relying too much on internal representation which may change in the future.

there's no out-of-the-box solution for what you seek. you'll have to implement that yourself.

i don't think there will be any breaking changes on the error representations unless there's a major architectural shift in the library - and there's no reason to anticipate such thing. just make sure you rely on the constants in `errors.py` and not on the integer codes for an error.

**Comment by funkyfuture** [comment]
is this resolved?
