### ISSUE TITLE
A dependency is not considered satisfied if it has a null value

### ISSUE THREAD

**Issue by derek-miller** [pyeve/cerberus#305]
Used Cerberus version / latest commit: 1.1

- I consulted these documentations:
  - [X] http://docs.python-cerberus.org/en/stable/
  - [ ] http://docs.python-cerberus.org/en/latest/

- I consulted these sections of the docs (add more lines as necessary):
  - http://docs.python-cerberus.org/en/stable/validation-rules.html#dependencies

- [X] I found nothing relevant to my problem in the docs.
- [ ] I found the documentation not helpful to my problem.

- [ ] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

----

#### Use-case abstract

A dependency is not considered satisfied if it has a null value.

----

#### Support request / Bug report
To reproduce:

```bash
>>> from cerberus import Validator
... validator = Validator(schema={
...     'field1': {
...         'required': False,
...         'nullable': True
...     },
...     'field2': {
...         'required': False,
...         'dependencies': 'field1'
...     }
... })
... document = {
...     'field1': None,
...     'field2': 'foo'
... }
... assert validator.validate(document), validator.errors
Traceback (most recent call last):
  File "<input>", line 16, in <module>
AssertionError: {'field2': ["field 'field1' is required"]}
```

This seems wrong considering required fields with a null value satisfy the required constraint, but not a dependency.

**Comment by funkyfuture** [comment]
does it also behave that way when defined without dependency?

my suspicion is that what you observe is rooted [here](https://github.com/pyeve/cerberus/blob/master/cerberus/validator.py#L1130).

if a field that is defined as `required` shall also fail when its value is `None` (my guess for now would be that this is intended), that fact should be amended to [the docs](http://docs.python-cerberus.org/en/stable/validation-rules.html#required).

**Comment by derek-miller** [comment]
No, a required field with a null value satisfies the ``required`` rule: 

```python
>>> from cerberus import Validator
... validator = Validator(schema={
...     'field1': {
...         'required': True,
...         'nullable': True
...     },
...     'field2': {
...         'required': False,
...         #'dependencies': 'field1'
...     }
... })
... document = {
...     'field1': None,
...     'field2': 'foo'
... }
>>> assert validator.validate(document), validator.errors
>>>
```
