### ISSUE TITLE
Defaults don't work in "allow_unknown" schema.

### ISSUE THREAD

**Issue by fomars** [pyeve/cerberus#310]
Used Cerberus version / latest commit: Cerberus==1.1

- I consulted these documentations:
  - [ ] http://docs.python-cerberus.org/en/stable/

- I consulted these sections of the docs (add more lines as necessary):
  - http://docs.python-cerberus.org/en/stable/normalization-rules.html
  - http://docs.python-cerberus.org/en/stable/validation-rules.html#allow-unknown

----

#### Use-case abstract

When I use "allow_unknown" property and specify some default in that "unknown" schema and then try to normalize a config, I expect that default to be fulfilled in normalized config.

----

#### Support request / Bug report

```
>>> CORE_SCHEMA = {'version': {'type': 'string'}, 'meta': {'type': 'dict'}}
>>> ALLOW_UNKNOWN_SCHEMA = {
...     'type': 'dict',
...     'schema': {
...             'package': {'type': 'string'},
...             'cfg_path': {'type': 'string', 'default': 'cfg.yaml'}
... }
... }
>>> v = Validator(CORE_SCHEMA, allow_unknown=ALLOW_UNKNOWN_SCHEMA)
>>> CONFIG = {'version': '1.2.3', 'core': {}, 'plugin_foo': {'package': 'foo'}}
>>> v.normalized(CONFIG)
{'core': {}, 'version': '1.2.3', 'plugin_foo': {'package': 'foo'}}
>>> EXPECTED_RESULT = {'version': '1.2.3', 'core': {}, 'plugin_foo': {'package': 'foo', 'cfg_path': 'cfg.yaml'}}


```

**Comment by funkyfuture** [comment]
i pledge to mark this for the `1.2` milestone.

**Comment by funkyfuture** [comment]
@fomars there's an inconsistency in your use-case as the `core` field isn't expected to have the defined default included. i'm removing that in the test case.
