### ISSUE TITLE
Feature: Regex caching

### ISSUE THREAD

**Issue by davidt99** [pyeve/cerberus#315]
When using the same validator and schema to validate multiple dictionaries, the same regex is compiled every time and thus might cause performance issues.
I think I can implement it, if this feature is accepted.

**Comment by funkyfuture** [comment]
afaik, the re module itself has a cache with compiled objects.

could you give an example?

**Comment by funkyfuture** [comment]
actually, i remember that i tested this out once for Cerberus, and a cache in Cerberus didn't make a difference.

**Comment by davidt99** [comment]
Hmm, you are right according to the [documentation](https://docs.python.org/3/library/re.html#re.compile). On python 3.5 the cache size is 512, but when the cache size exceeds the limit, the whole cache is cleared. I guess under certain condition, this can cause a performance issue. 
Considering this, the current implementation is sufficient enough for almost all cases but maybe it worth mentioning in the documentation.
In any case, I think this issue can be closed.

**Comment by nicolaiarocci** [comment]
Thanks @davidt99!
