### ISSUE TITLE
How to validate multi select drop down ?

### ISSUE THREAD

**Issue by srikanth148** [pyeve/cerberus#319]
multi-select boxes return list of elements not listed. how to validate multi select drop down?

![image](https://user-images.githubusercontent.com/26059420/27435456-ebc6b998-5779-11e7-9e68-5405188ce367.png)

**Comment by andreymal** [comment]
`QueryDict`  is magical and `request.POST['start_time']` returns last value, use `validate(dict(request.POST))` to fix this

Remember that `dict(request.POST)` values have always lists of strings

**Comment by srikanth148** [comment]
thank you, how to handle conversion of empty string into an integer and  I like to allow empty values also

**Comment by funkyfuture** [comment]
this question i suited for [SO](https://stackoverflow.com/questions/tagged/cerberus).
