### ISSUE TITLE
Incorrect `validator` docs

### ISSUE THREAD

**Issue by leebenson** [pyeve/cerberus#320]
I spent about an hour trying to implement a custom `validator` per http://docs.python-cerberus.org/en/stable/customize.html, and finally realised that the docs are wrong!

This:

```py
class MyValidator(Validator):
    def _validate_isodd(self, isodd, field, value):
```

should be:

```py
class MyValidator(Validator):
    def _validator_isodd(self, isodd, field, value):
```

i.e. `_validate_` -> `_validator_`

**Comment by funkyfuture** [comment]
disclaimer: i might be wrong as i'm quiet tired.

the `_validate_`-prefix is used for custom *rules* (`isodd` in the example) while `_validator_` is for the [`validator`](http://docs.python-cerberus.org/en/stable/validation-rules.html#validator) rule (which doesn't require to subclass `Validator`, but does't allow to define constraints in schemas). if i'm not wrong, it nonetheless raises the point that the documentation should be more verbose on that difference. contributions in this regard are highly appreciated!

**Comment by leebenson** [comment]
Thanks - makes sense @funkyfuture. I agree that the docs could do with a clarification- it definitely wasn't obvious to me that `_validator_` and `_validate_` were two different concepts.

**Comment by funkyfuture** [comment]
i pledge to mark this for the `1.2` milestone.

**Comment by bryanwweber** [comment]
FWIW, I also asked a question on StackOverflow about this topic: https://stackoverflow.com/q/39438774/2449192 @nicolaiarocci Answered me there as well, but I didn't quite understand his answer.

**Comment by funkyfuture** [comment]
@bryanweber, i edited Nicola's answer yesterday or the day before to point a major difference. i notice, i should amend an example (put a link to one now). if there's still clarification needed, please let us know.

one thought: maybe we shouldn't talk of '*custom* validators', there are no standard ones, so *custom rule* vs. *validator*.
