### ISSUE TITLE
Have purge_unknown and allow_unknown play nice together

### ISSUE THREAD

**Issue by audricschiltknecht** [pyeve/cerberus#324]
# Issue
(Unless I am missing something)
Setting `purge_unknown` on Validator (or top-level schemas) will ignore specific `allow_unknown` properties on fields.

The use-case is that while undeclared fields should be purged from the document, there are some of the sub-documents that have been explicitly tagged as permitting unknown fields, and these should not be purged.

# Reproduce
- First example
```
>>> validator = Validator(purge_unknown=True)
>>> schema = {'foo': {'type': 'dict', 'allow_unknown': True}}
>>> document = {'foo': {'bar': True}, 'bar': 'foo'}
>>> validator.validated(document, schema)
{'foo': {}}
```
Expected:
```
{'foo': {'bar': True}}
```
- Second example
```
validator = Validator(purge_unknown=True)
schema = {'foo': {'type': 'dict', 'schema': {'bar': {'type': 'string'}}, 'allow_unknown': True}}
document = {'foo': {'bar': 'baz', 'corge': False}, 'thud': 'xyzzy'}
>>> validator.validated(document, schema)
{'foo': {'bar': 'baz'}}
```

Expected:
```
{'foo': {'bar': 'baz', 'corge': False}}
```

**Comment by audricschiltknecht** [comment]
I have implemented a small patch https://github.com/audricschiltknecht/cerberus/commit/07b61edebcc1a08f1725cb00c82c99de61a3501b
If there is interest, I can create a pull-request for this.

**Comment by funkyfuture** [comment]
imo, it's reasonable to address and merge that.

this means that `allow_unknown` and `purge_unknown` should be declared as mutually exclusive, both in the validator of schemas and the configuration of a validator instance.

**Comment by audricschiltknecht** [comment]
@funkyfuture thanks for your comment.
However, I do not think that they should be mutually exclusive, but that `allow_unknown` will have precedence on `purge_unknown` where defined (this is our use-case). Am I making sense?

**Comment by funkyfuture** [comment]
yes, it makes sense. my intent is to avoid questions from users who are not aware of that behaviour by telling them upfront what they shouldn't expect to function as they may expect that.

**Comment by nicolaiarocci** [comment]
@audricschiltknecht please submit a PR for this. Make sure the docs are updated, maybe with the very same example you posted here, so users know what the intended behavior is.

**Comment by audricschiltknecht** [comment]
Ok, will do

**Comment by audricschiltknecht** [comment]
I've just created a PR. However, I could not run doc creation nor doctests because of an error raised by sphinx (neither using my virtualenv nor by running the docker script).
