### ISSUE TITLE
Need to drop rules when empty is allowed

### ISSUE THREAD

**Issue by crsharat** [pyeve/cerberus#326]
I dont know how to explain the issue but will share my code.

![screenshot from 2017-07-19 11-38-39](https://user-images.githubusercontent.com/12701777/28352948-e4d536ac-6c76-11e7-9ac1-58b473a47cdf.png)

It should not check for regex if data is empty.

Thanks

**Comment by funkyfuture** [comment]
i pledge to mark this for the `1.2` milestone.

this can easily be realized with `Validator._drop_remaining_rules`.
