### ISSUE TITLE
Customizing message for a list document

### ISSUE THREAD

**Issue by junaruga** [pyeve/cerberus#329]
Used Cerberus version / latest commit: ...
1.1 (latest version)

- I consulted these documentations:
  - [X] http://docs.python-cerberus.org/en/stable/
  - [X] http://docs.python-cerberus.org/en/latest/

- I consulted these sections of the docs (add more lines as necessary):
  - "Validation Rules"
  - "Errors & Error Handling"
  - Stackoverflow

- [ ] I found nothing relevant to my problem in the docs.
- [X] I found the documentation not helpful to my problem.

- [ ] I have the capacity to improve the docs when my problem is solved.
- [X] I have the capacity to submit a patch when a bug is identified.

----

#### Use-case abstract

PLEASE SUMMARIZE YOUR USE-CASE

This is a feature request, related to customize error message.
It is a improvement for a list document's errors text.
I would like to explain with a sample code [1]

```
$ python3 cerberus_test.py
errors: {'a_list': [{2: [{'value': ['must be of integer type']}], 3: [{'value': ['must be of integer type']}]}]}
```

[1] https://gist.github.com/junaruga/3598ccc5cef1b3e75c10c1dad5317887

a_list (list) has 100 elements. each element is dict. and has name key.
If error is outputted, the element number is outputted.
But I want `name`'s value such as `a3`, `a100` in errors object to output below error messages.

```
a list - a3 [2] - 'value': ['must be of integer type']
a list - a100 [3] - 'value': ['must be of integer type']
```

How do you think?

Thank you.

**Comment by funkyfuture** [comment]
if i understand you correctly, you want to include a neighbour's field value into the error message for a field. this can obviously not be generalised and thus you're propably best off by customizing `errors.BasicErrorHandler`. if further methods on that one would be useful for customizations in general, a pull request with these are certainly welcome.

**Comment by funkyfuture** [comment]
by the way, this is a suitable question for [StackOverflow](https://stackoverflow.com/questions/tagged/cerberus).

**Comment by junaruga** [comment]
Thank you for the replying. I may send pull request in the future. But do not expect it :)
Sorry I should ask in StackOverflow.
So, right now I would lose this ticket.
