### ISSUE TITLE
KeyError: 'schema' occurs when 'allow_unknown' is present without 'schema'

### ISSUE THREAD

**Issue by TMiguelT** [pyeve/cerberus#330]
Cerberus Version: 1.1
Python Version: 2.7.12

If you run this code, you will get `KeyError: 'schema'`, because cerberus tries to find a schema property in the `a_dict` entry that does not exist:
```python
import cerberus

validator = cerberus.Validator()
schema = { 
    'a_dict': {
        'type': 'dict',
        'allow_unknown': True
    }   
}
document = { 
    'a_dict': {
        'some_key': 1
    }   
}
validator.validate(document, schema)
```

If you remove the `allow_unknown` key, there will be no error:
```python
schema = { 
    'a_dict': {
        'type': 'dict'
    }   
}
```

I think this behaviour is confusing. Perhaps, if there is no schema, `allow_unknown` could be silently ignored, because it's implied by the lack of schema. If you'd rather keep the behaviour how it is, maybe there could be a proper error message that says "you need a schema if you want to use `allow_unknown`".

Thoughts?

**Comment by funkyfuture** [comment]
this is already fixed with the code in this repository.

**Comment by TMiguelT** [comment]
Oh, as in a version that hasn't yet been released on pip?

**Comment by funkyfuture** [comment]
exactly. see [details](http://docs.python-cerberus.org/en/stable/install.html#development-version) on installing a development version. `pip` is also capable of installing from a git repo and a specified branch.
