### ISSUE TITLE
docs build are failing due to an unknown cause

### ISSUE THREAD

**Issue by funkyfuture** [pyeve/cerberus#333]
i just realized that the [failing doc build](https://travis-ci.org/pyeve/cerberus/jobs/265717785#L549) isn't caused by #281.

it started to fail on my local setup after i upgraded Sphinx. with 1.5.6 it's alright.

[this](https://github.com/celery/sphinx_celery/pull/2) raised my suspicion that it may be caused by [sphinxcontrib-issuetracker](https://pypi.python.org/pypi/sphinxcontrib-issuetracker) which hasn't been updated for over four years.

i opened https://github.com/ignatenkobrain/sphinxcontrib-issuetracker/issues/12.

**Comment by funkyfuture** [comment]
there's a pull request pending, that should solve this issue: https://github.com/ignatenkobrain/sphinxcontrib-issuetracker/pull/13

**Comment by nicolaiarocci** [comment]
Nice catch.

**Comment by funkyfuture** [comment]
alternatively we could change to the [extlinks](http://www.sphinx-doc.org/en/stable/ext/extlinks.html) extension that is shipped with Sphinx and thus remove a dependency.
