### ISSUE TITLE
Error when trying for number or integer validation 

### ISSUE THREAD

**Issue by phoenix911** [pyeve/cerberus#350]
Used Cerberus version:  Cerberus==1.1

- I consulted these documentations:
  - [✓ ] http://docs.python-cerberus.org/en/stable/
  - [✓ ] http://docs.python-cerberus.org/en/latest/

- [✓ ] I found nothing relevant to my problem in the docs.
- [ ✓] I found the documentation not helpful to my problem.

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ✓] I have the capacity to submit a patch when a bug is identified.

----

#### Use-case abstract

I'm trying to validate integer or number type 
----

#### Support request / Bug report

I'm using cerberus with falcon to validate my requests. 
my schema is 
schema = {
    'phone': {
        v.type_: "integer",
        v.maxLength: 10,
        v.required: True
    }, 'password': {
        v.type_: v.type_str,
        v.minLength: 6,
        v.required: False
    }, 'email': {
        v.type_: v.type_str,
        v.required: True,
        v.regex: v.regex_email
    }
}

but whenever i'm sending integer as my phone parameter I'm getting following error message
{
        "phone": [
            "must be of integer type"
        ]
}

**Comment by funkyfuture** [comment]
- could you please use code formatting
- also provide sample data that fails
- what is this `v` object?
- nice sqr usage

**Comment by funkyfuture** [comment]
this issue can be closed, right?
