### ISSUE TITLE
Validation of list for mandatory values

### ISSUE THREAD

**Issue by zDawG** [pyeve/cerberus#351]
Hi there!
I want to use cerberus to validate that a list has all the authorized values.
Example might be:

`msg = ['abc', 'def', 'ghi']`

I need all three of those values to be in the list but the order is not guaranteed.
How would I write a cerberus schema to validate that all those values are there?
I know I can use 'allowed' but it will still come back as true if only two of those values are there.

Outside the framework I could do something like:
`'abc' in msg and 'def' in msg and 'ghi' in msg`

but I want to be able to do this purely in cerberus if I can.

I've been over the docs and tried to use 'allof' on a list but haven't been able to make it work.

**Comment by funkyfuture** [comment]
individual's problem solving questions are suitable to be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/cerberus).
