### ISSUE TITLE
schema for field named "type" (not type of field, but field type lol)

### ISSUE THREAD

**Issue by vsmelov** [pyeve/cerberus#353]
I want to validate JSON from WEB-requests like
{"type": "people", "age": 18, "sex": "M"}

so i try to create schema
{
    'type': {'type': 'string'},
    'age': {'type': 'integer'},
    'sex': {'type': 'string'}
}

but at the moment of validation got error.
TypeError: 'NoneType' object is not callable

I think it is because of conflict in type as a type of field, and type as a name of field.

How to fix it?

**Comment by funkyfuture** [comment]
works for me with the current master branch's state.
