### ISSUE TITLE
[feature] add support for metadata keys in schema

### ISSUE THREAD

**Issue by yagnik** [pyeve/cerberus#355]
Currently any additional fields in the schema gives an "unknown rule" error.
We are looking to add support for metadata fields or any extra fields in the schema. 
I'll be more than happy to add this feature if you can point me in the right direction.

- I consulted these documentations:
  - [x] http://docs.python-cerberus.org/en/stable/
  - [x] http://docs.python-cerberus.org/en/latest/

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

----

#### Use-case abstract

PLEASE SUMMARIZE YOUR USE-CASE

```
schema = {
  "type": "string",
  "required": True,
  "metadata": "foobar"
}
```

**Comment by yagnik** [comment]
From my understanding so far, if just make this: https://github.com/pyeve/cerberus/blob/b8b26f927c9cdd093254439e0841e551dce51abf/cerberus/schema.py#L239 configurable that should do the job for us. wdyt ?

**Comment by funkyfuture** [comment]
so, if i understand correctly, you want to store data about a field that is not a rule. let's say:

```yaml
user:
  type: string
  regex : [a-z-]{8,}
  label: Your username
  help: Enter your username to identify yourself.
```

as any `Validator` has a `rules` attribute that contains all rules the validator implements, you can use that to  strip non-rule keys from a field's definition.

do you want to include such logic in Cerberus itself?

**Comment by yagnik** [comment]
while I'd love that to be part of cerberus itself, I guess it's implementation would be a"custom" validator.
If you think it won't be a good decision then you are welcome to close it and Ill use the custom validator

**Comment by funkyfuture** [comment]
if someone wants to take on  that, here are some thoughts:

- this behaviour should be controlled by a validator's init-option and property that are passed to a `DefinitionSchema`'s initialization.
- the superfluous fields in a defintion should be stripped before the schema gets expanded (`DefinitionSchema.expand`).
- the schema-initialization/validation code is somewhat twisted as it uses Cerberus and is thus assembled quiet dynamically. so expect pitfalls - but there are often simple paths to circumvent these.

**Comment by yagnik** [comment]
I'll see if I get time to tackle this :)
Thanks for the pointers!
