### ISSUE TITLE
Include a link to Nicola's talk at PiterPy in the docs

### ISSUE THREAD

**Issue by funkyfuture** [pyeve/cerberus#357]
i'd like to put a reference to @nicolaiarocci's [talk at the PiterPy](https://www.youtube.com/watch?v=vlHAjIPvoT4) in the docs. but i have no idea what a good spot would be. is anyone aware of other Cerberus related resources that are hosted by a third party?

**Comment by nicolaiarocci** [comment]
That's embarrassing 😄 

Besides that, I don't think we have anything similar right now in the docs?

**Comment by funkyfuture** [comment]
> I don't think we have anything similar right now in the docs?

that's why i opened this issue, otherwise i'd had submitted a patch already. would be even more embarrasing, right?

the only recommendable further resource a quick research revealed was this article: https://codingnetworker.com/2016/03/validate-json-data-using-cerberus/

**Comment by nicolaiarocci** [comment]
Creating an external resources page is probably a good idea. Could even encourage people to write their own blog posts/articles etc. on the project.
