### ISSUE TITLE
UserWarning while running sample code for  class-based Validator

### ISSUE THREAD

**Issue by olegsv** [pyeve/cerberus#366]
I have copied an example code for class-based Validator from here : http://cerberus-sanhe.readthedocs.io/customize.html#class-validator

```
from cerberus import Validator

class MyValidator(Validator):
    def _validate_isodd(self, isodd, field, value):
        if isodd and not bool(value & 1):
            self._error(field, "Must be an odd number")

```
Unfortunately the code emits user warning: (python3.5, cerberus 1.1)

```
/usr/local/lib/python3.5/dist-packages/cerberus/validator.py:1338: UserWarning: No validation schema is defined for the arguments of rule 'isodd'
  "'%s'" % method_name.split('_', 2)[-1])

```

**Comment by funkyfuture** [comment]
where is that resource originating from? please consult the docs provided by @nicolaiarocci.

the UserWarning fortunately works as expected.

**Comment by olegsv** [comment]
@funkyfuture turns out the docstring is important. The following code works:

```
class MyValidator(Validator):
    def _validate_isodd(self, isodd, field, value):
        """ Test the oddity of a value.
        The rule's arguments are validated against this schema:
        {'type': 'boolean'}
        """
        if isodd and not bool(value & 1):
            self._error(field, "Must be an odd number")

```

**Comment by funkyfuture** [comment]
i know. but do you know what resource that is you quoted and how did you come come across it?

**Comment by olegsv** [comment]
Looks like an old fork of cerberus. My bad for not looking for the exact URL.

**Comment by D-stefaang** [comment]
Note that you need to include this text literally
```
        The rule's arguments are validated against this schema:
```
