### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by davidt99** [pyeve/cerberus#367]
The last release was in january 2017. Any chance for a new release in PyPi, even a rc1 one?

**Comment by nicolaiarocci** [comment]
@funkyfuture I think we're ready for a 1.2 release?

**Comment by funkyfuture** [comment]
the only thing i wanted to adjust was the milestone link in the roadmap, but you already took care of that.

happy releasing! :champagne:

**Comment by nicolaiarocci** [comment]
It's out.
