### ISSUE TITLE
Add None as constraint to allowed when nullable and allowed are defined on a field

### ISSUE THREAD

**Issue by radix** [pyeve/cerberus#373]
Example schema:

```python
>>> v = cerberus.Validator({
...     'x': {
...         'nullable': True,
...         'oneof': [{'type': 'string'}, {'type': 'number'}]}})

# As expected:
>>> v.validate({'x': 'foo'})
True
>>> v.validate({'x': 52})
True
>>> v.validate({'x': object()})
False

# Unexpected:
>>> v.validate({'x': None})
False
```

Used Cerberus version / latest commit: b8b26f927c9cdd093254439e0841e551dce51abf

- I consulted these documentations:
  - [x] http://docs.python-cerberus.org/en/stable/
  - [x] http://docs.python-cerberus.org/en/latest/

- I consulted these sections of the docs (add more lines as necessary):
  - Validation Rules

- [x] I found nothing relevant to my problem in the docs.
- [x] I found the documentation not helpful to my problem.

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

**Comment by funkyfuture** [comment]
everything works as expected. but indeed, it raises the point that there is no `None` type which would make this schema much simpler.

mind that `type` can take multiple constraints.

**Comment by radix** [comment]
if "nullable can be used with oneof", what behavior does it affect?

**Comment by radix** [comment]
So... there's no effect?

**Comment by deanolium** [comment]
The same happens with allowed and nullable. You can add None at least in the allowed array, but this should be implied (ie, you need both None in the allowed array and 'nullable' to be set to True). Incredibly counter-intuitive

**Comment by funkyfuture** [comment]
> Incredibly counter-intuitive

i'd argue that it'd be counter-intuitive when one rule with a certain constraint changes the semantics of another rule within a shared context.

**Comment by funkyfuture** [comment]
problem is: we're both right. also, i can't come up with something such schema alteration could mess up.

**Comment by radix** [comment]
@funkyfuture Cerberus's behavior is inconsistent with your analysis:

> your schema snippet says, the value can be None AND (must be a string OR a number).

What does a schema that says `{'type': 'string', 'nullable': True}` mean?

Does it mean "the value can be None AND the value must have type `string`"? No, cerberus treats this as an OR. So why would it suddenly become an `AND` in the face of `oneof`?

**Comment by funkyfuture** [comment]
could you please check out whether 74caea64b3d3a13c27f3dede0d59e8d3c0fd11aa solved this issue?

**Comment by Prudhvee** [comment]
Even I get unallowed value None for the schema {'type': 'string', 'allowed': ('min', 'max'), 'nullable': True}
for None value over the string. Is it expected?

**Comment by christabone** [comment]
I'm seeing the same behavior as well (loading schema from yaml). My "P30" field is currently blank in this example:

Schema:
```
P30:
  required: False
  type: string
  nullable: True
```
Custom debug output:
```
DEBUG -- Error items below:
DEBUG -- Field value is None
DEBUG -- Field is P30, values is ['must be of string type']
WARNING -- P30: must be of string type
```

**Comment by christabone** [comment]
It can be fixed with the following change to the schema. A bit less-than-ideal, but it works:

Schema:
```
P30:
  required: False
  oneof:
    - nullable: True
    - type: string
```

**Comment by funkyfuture** [comment]
i assume that this issue is  either solved with the previously mentioned commit or this one: 35d9f7b79f6afd165568db9671441a8f41cf34cf.
