### ISSUE TITLE
Custom rules has stoppe working in Cerberus 1.2

### ISSUE THREAD

**Issue by ThreePinkApples** [pyeve/cerberus#379]
- [x] I found nothing relevant to my problem in the docs.
- [x] I found the documentation not helpful to my problem.

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

----

A simple custom rule, constant
----

We've been using a custom rule named 'constant' for quite some time now, but after upgrade to Cerberus 1.2 it crashes with this:
```
RuntimeError: There's no handler for 'constant' in the 'validate' domain.
```

Our validator:

```
class MetadataValidator(Validator):
    def _validate_constant(self, constant, field, value):
        '''{'constant': {'required': True}}'''
        if value != constant:
            self._error(field, '{!r} != expected constant {!r}'.format(
                value, constant))
```

The scheme:

```
{'metadata_version': {'type': 'integer', 'constant': 3, 'required': True}}
```

**Comment by funkyfuture** [comment]
now, this is very odd. i added this test to the test suite:

```python
def test_issue_379():
    class MetadataValidator(cerberus.Validator):
        def _validate_constant(self, constant, field, value):
            if value != constant:
                self._error(field, '{!r} != expected constant {!r}'.format(
                    value, constant))

    schema = {'metadata_version': {'type': 'integer', 'constant': 3, 'required': True}}
    validator = MetadataValidator(schema)

    assert 'constant' in validator.validation_rules
    assert validator.validate({'metadata_version': 3})
    assert not validator.validate({'metadata_version': 2})
```

the first time i ran the test, it failed. but any further time it didn't. it also doesn't fail in a freshly created tox environment.

could y'all please provide info what Python version is used, how Cerberus was installed and the value of `cerberus.__version__`? cc @karthikb351 @Luckjanov

**Comment by funkyfuture** [comment]
see also #377.

**Comment by ThreePinkApples** [comment]
Ah dug some more today, was a bit confusing (I'm just a maintainer, haven't dealt with Cerberus before). 
The issue was the rules argument validation. That's the one that failed with 'constant' not being defined, I guess Cerberus just ignored that issue before maybe?
Broken in 1.2
```
class MetadataValidator(Validator):
    def _validate_constant(self, constant, field, value):
        """{'constant': {'required': True}}"""
        if value != constant:
            self._error(field, '{!r} != expected constant {!r}'.format(
                value, constant))
```
Fixed
```
class MetadataValidator(Validator):
    def _validate_constant(self, constant, field, value):
        """{'type': 'integer'}"""
        if value != constant:
            self._error(field, '{!r} != expected constant {!r}'.format(
                value, constant))
```

**Comment by funkyfuture** [comment]
> Broken in 1.2

what does this mean?

**Comment by ThreePinkApples** [comment]
> what does this mean?

Sorry, clarified what I meant now

**Comment by funkyfuture** [comment]
hence, this issue can be closed, right?

**Comment by ThreePinkApples** [comment]
Yes!
