### ISSUE TITLE
Request: Regex MULTILINE implementation 

### ISSUE THREAD

**Issue by marian-daogaru** [pyeve/cerberus#389]
Hello team! 

In `Validator._validate_regex` it was recently added that if the regex pattern does not end with **$**, it will be added to the pattern. However, this is sometimes problematic for multi-line string as it will match properly what is desired. 

Do you think it would be possible to added a flag to enable `re.MULTILINE` to be added to the `re_obj.match(value)`.

Thank you!

**Comment by coltenwebb** [comment]
Correct me if I'm wrong, but you should be able to pass `re.MULTILINE` as a part of the of the pattern itself. Just include [`(?m)`](https://docs.python.org/3.6/library/re.html#regular-expression-syntax) at the beginning of the pattern.

**Comment by funkyfuture** [comment]
that [part of the docs](http://docs.python-cerberus.org/en/stable/validation-rules.html#regex) could certainly use improvement.
