### ISSUE TITLE
How Can I Check a Number is a Certain Length in Cerberus?

### ISSUE THREAD

**Issue by Nerldy** [pyeve/cerberus#391]
Hello,

I'm writing a book schema with Cerberus but I've stumbled upon a block. I want the ISBN field to accept a number/integer/digit that is either exactly 10 digits long, or exactly 13. How can I go about that? I tried using maxlength and minlength but they don't seem to work.

**Comment by funkyfuture** [comment]
since you have a usage question that you also asked on Stackoverflow, please close this issue to maintain thes issues list to relevant bug reports and feature discussions.
