### ISSUE TITLE
nullable is ignored in schemas with 'allowed'

### ISSUE THREAD

**Issue by crunk1** [pyeve/cerberus#400]
Used Cerberus version / latest commit: 1.2

- I consulted these documentations:
  - [x ] http://docs.python-cerberus.org/en/stable/
  - [x] http://docs.python-cerberus.org/en/latest/

- [x] I found nothing relevant to my problem in the docs.
- [x] I found the documentation not helpful to my problem.

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

----

#### Use-case abstract

I want to limit the values of a string via, i.e. `allowed` values, but I also want the field to be nullable.
Example:

```python 
>>> schema = {'foo': {'type': 'string', 'allowed': ['bar'], 'nullable': True}} 
>>> v = Validator(schema)
>>> v.validate({})
True
>>> v.validate({'foo': 'bar'})
True
>>> v.validate({'foo': 1})
False
>>> v.validate({'foo': 'gaz'})
False
>>> Validator({'foo': {'type': 'string', 'nullable': True}}).validate({'foo': None})  # True when not using 'allowed'
True
>>> v.validate({'foo': None})  # I want this to be True
False
```

----

#### Support request / Bug report
`'nullable'` is ignored when `'allowed'` is used.

I've also tried 
```python 
>>> schema = {'foo': {'type': 'string', 'allowed': ['bar', None], 'nullable': True}}
```

but that doesn't work.

**Comment by crunk1** [comment]
```python
>>> v._errors
[ValidationError @ 0x7f2fa3a92828 ( document_path=('foo',),schema_path=('foo', 'allowed'),code=0x44,constraint=['bar'],value=None,info=(None,) )]
```

**Comment by funkyfuture** [comment]
this works for me:

```python
def test_allowed_and_nullable():
    # https://github.com/pyeve/cerberus/issues/400
    schema = {'foo': {'type': 'string', 'allowed': ['bar', None], 'nullable': True}}
    assert_success({'foo': None}, schema)
```

is this what you expect?

**Comment by crunk1** [comment]
Hmm, weird. I retested it with 'None' in `allowed` and it worked. I could have sworn I tested that before. Apologies!
