### ISSUE TITLE
Adopt Black code-style. Also add support for pre-commit workflow.

### ISSUE THREAD

**Issue by nicolaiarocci** [pyeve/cerberus#402]
I am loving the new workflow we have in Eve. With Black and other linters/fixers hooked into pre-commit, we have a code standard guarantee which also happens to be remarkably readable. 

As mentioned in #383, what about doing the same thing with Cerberus?

**Comment by funkyfuture** [comment]
i hope a lot, that this makes it easier for contributors and reviewers. with regards to eve, it totally makes sense. there's just one thing that i really don't like: forced double quotes (and i know that i'm sentimental here). so i'd say we opt that out. would there something to be minded now for the case that black may be dropped again?

**Comment by funkyfuture** [comment]
i set this to the 1.3 milestone. okay?

**Comment by nicolaiarocci** [comment]
Yes, I am not particularly fond of the double quote thing. When I added it to Eve there was no opt-out option and now it is a little bit too late (I have to admit that once the code has been reformatted, it looks pretty even with the doubles! - and you can keep coding with singles, black will fix them for you). Ok with the 1.3 milestone.

**Comment by nicolaiarocci** [comment]
PS: besides all the ramblings, I'm fine with opting out of the double quotes.

**Comment by funkyfuture** [comment]
[pytest now styles its docs with black.](https://github.com/pytest-dev/pytest/pull/3528) well, the code snippets in it.
