### ISSUE TITLE
Let's rename the 'validator' rule to 'check_with'

### ISSUE THREAD

**Issue by funkyfuture** [pyeve/cerberus#405]
as we are evolving a concept for the next major release, we have the opportunity for a thing i like best: breaking things.

i'm not very fond of the circumstance that the number one object of the library and a default rule it provides have the same name: `validator`.

it makes especially communicating to humans about Cerberus harder and potentially misleading. it probably also doesn't help to conceptualize Cerberus (or the opposite, who knows, depending on the recipient). in some client code this may resolve in longer or confusing variable names. (users that read code that makes use of Cerberus and don't know more about it than its designation - which is obvious due to the names `validate` etc. - are an audience to be considered as well.)

what could be another name that describes the rather autonomous validation rule `validator` that offers a lot of leverage and requires more than entry-level effort by users? it should not include more than two morphemes, ten chars max seems reasonable, and no short hamming distance to any other relevant term obviously.

if renamed, a deprecation layer could easily be provided, as no other rule with that name would be added ever again.

**Comment by nicolaiarocci** [comment]
- `validate_with`
- `validate_function`

?

There are probably better options out there. Agree on the deprecation period.

**Comment by funkyfuture** [comment]
your first is my fav so far, i came up with

* `check`
* `checker`

and now

* `check_with`

the `_with` variants fit best for both single and multiple 'validators' that may be provided as constraints.

**Comment by nicolaiarocci** [comment]
`check_with` is nice, yes. Concise and yet clear.

**Comment by nicolaiarocci** [comment]
I guess we want the new name to go live with 1.3, so we can drop the old one with 2.0?
