### ISSUE TITLE
how does  cerberus count maxlength if it's 2byte character like japanese?

### ISSUE THREAD

**Issue by ts-kazuo-ieiri** [pyeve/cerberus#410]
how does  cerberus count maxlength if it's 2byte character like japanese?

**Comment by funkyfuture** [comment]
it does so by [asking the builtin len function](https://github.com/pyeve/cerberus/blob/00835837e550a12c195628247a51c7bd27ea2f86/cerberus/validator.py#L1174). i guess you relate your question to a usage with strings where actually the number of unicode code points is returned by this function. you are probably well served by implementing a rule that makes use of the capabilities provided by the [grapheme](https://pypi.org/project/grapheme/) package.
