### ISSUE TITLE
Add stale-bot to close stale issues and pull requests

### ISSUE THREAD

**Issue by nicolaiarocci** [pyeve/cerberus#415]
[stale-bot](https://github.com/probot/stale) is a useful tool to keep tickets under control and manageable. We already activated it on the Eve repository with excellent results.

The rationale is as follows (quoting from the repository README):

# Is closing stale issues a good idea?

In an ideal world with infinite resources, there would be no need for this app.

But in any successful software project, there's always more work to do than people to do it. As more and more work piles up, it becomes paralyzing. Just making decisions about what work should and shouldn't get done can exhaust all available resources. In the experience of the maintainers of this app—and the hundreds of other projects and organizations that use it—focusing on issues that are actively affecting humans is an effective method for prioritizing work.

To some, a robot trying to close stale issues may seem inhospitable or offensive to contributors. But the alternative is to disrespect them by setting false expectations and implicitly ignoring their work. This app makes it explicit: if work is not progressing, then it's stale. A comment is all it takes to keep the conversation alive.

**Comment by funkyfuture** [comment]
with some reasonable exceptions per labels, sure. if you say that there are good experiences. i just wonder how that's good with comments that essentially say '+1' or 'any progress?'.

**Comment by nicolaiarocci** [comment]
You can dictate which labels should be ignored by the bot, yes. Not sure on +1s, 'any progress?' is a comment, so it un-stales a ticket.

**Comment by funkyfuture** [comment]
okay, it's a tool. so it helps with but doesn't conclude decisions. ;-)

(btw, i meant the 'old' plain text +1s, but that hasn't been much of an issue here anyway.)

**Comment by Morriz** [comment]
So funny that this is not marked "stale" after more than two years ;p

**Comment by funkyfuture** [comment]
given that we're aiming to stick with the low-maintenance course we can expect that issues are either solved after quiet a while or not solved at all but some should stay visible due to popularity, i close this proposal.
