### ISSUE TITLE
Allow unknown keys but validated subs schemas

### ISSUE THREAD

**Issue by CJ-Wright** [pyeve/cerberus#416]
Used Cerberus version / latest commit:

cerberus                  1.2                      py36_0    conda-forge

- [x] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve. [I have a practical use case for this issue, I can't seem to get things to operate properly, I'm not certain if this box applies to me?]

----

#### Use-case abstract

I'd like to have a sub schema where the top level keys are unknown (eg the ids for the entries) but the sub schema beneath that are validated.
for example

----

#### Bug report / Feature request

```python
data = {
'name': 'test',
'department': {
    'unknown_key': {
        'known_key': 'good',
        'unknown_key': 'bad'
    }
}}

schema = {
'name': {
    'type': 'string'
},
'department': {
    'type': 'dict',
    'allow_unknown': {
        'schema': {
            'type': 'dict',
            'schema': {'known_key': {'type': 'string'},
                       'must_have_key': {'type': 'string'}}}
    },
}}
v = Validator(schema)
v.validate(data)  # is True
```
But this has failed as the validation passes. It should have failed on both the missing `must_have_key` and the `unknown_key`.

SO question: https://stackoverflow.com/questions/50994398/allow-unknown-keys-but-validated-values-in-schema

**Comment by CJ-Wright** [comment]
Sorry for the delay, I'll try to put in a docs PR in the near future.

**Comment by funkyfuture** [comment]
closing this to reduce issue noise, but improvements in this regard are still welcome.
