### ISSUE TITLE
Proposal: Add an option to require all defined fields of a schema

### ISSUE THREAD

**Issue by pohmelie** [pyeve/cerberus#417]
There are four cases which I think should be covered with validator instance arguments:
* Allow known missed, forbid unknown present (default behavior right now)
* Allow known missed, allow unknown present (`allow_unknown=True`)
* Forbid known missed, forbid unknown present (no way at validator creation time)
* Forbid known missed, allow unkown present (no way at validator creation time)

Cerberus have `allow_unknown` option for validator, but have no `allow_known_missed` / `forbid_known_missed` or something like this. As [stackoverflow](https://stackoverflow.com/questions/45935812/have-required-set-to-true-by-default-in-cerberus) question said, it is pretty annoying to set `required: True` for all fields, cause they can be nested and schema looks noisy and dirty.

**Comment by pohmelie** [comment]
It looks like this can be achieved, by changin couple of places, where `'required'` checked to something like:
``` python
self.schema[field].get('required', self.forbid_known_missed)
```

**Comment by pohmelie** [comment]
Ok, I have successfully patched cerberus `validator.py` with technic like above, tests are still ok and looks like added argument works fine. The only problem is since `'required'` became orphan there is an error [here](https://github.com/pyeve/cerberus/blob/master/cerberus/validator.py#L284), but I hope this can be resolved.

**Comment by funkyfuture** [comment]
if this gets added, i'd prefer the option name `require_all`. some form of `required` is needed in the name to clearly relate it to the `required` rule.

should there also be a same-named flag for (sub-)schemas like `allow_unknown`?

**Comment by funkyfuture** [comment]
@pohmelie a feedback on the progress would be great to have rather soonish as we're getting closer to the next minor release after which new features can't be merged for a while due to planned, larger code changes.
