### ISSUE TITLE
Regex is ignored when using custom coercion

### ISSUE THREAD

**Issue by elben10** [pyeve/cerberus#428]
#### Use-case abstract

It seems like that regexes is simply ignored, when using a coercing function. I would expect that if the input is a string the regex validation shouldn't be affected by the coercion function. 

----

#### Bug report / Feature request

```python
>>> # Import library
... 
>>> from cerberus import Validator
>>> 
>>> 
>>> # Define custom coerce function
... 
>>> def custom_coerce(x):
...         if x is True:
...                 return 'true'
...         else:
...                 return 'false'
... 
>>> 
>>> # Define schemas
... 
>>> schema1 = {
...     'test': {
...         'type': 'string',
...         'regex': '^true$',
...         'coerce': (bool, custom_coerce)
...     }
... }
>>> 
>>> schema2 = {
...     'test': {
...         'type': 'string',
...         'regex': '^true$',
...     }
... }
>>> 
>>> # Initiate validator
... 
>>> v = Validator()
>>> 
>>> v.validate({'test': 'ThisShouldConflictWithRegex'}, schema1) # Should return False
True
>>> v.validate({'test': 'ThisShouldConflictWithRegex'}, schema2)
False
```

But it seems like that the actual coercion works with the regex. If the coercion function is supplied then `{'test': True}` is validated to `True` if the coercion function is not supplied `{'test': True}` is validated to false. This behaviour is as expected.

```python
>>> v.validate({'test': True}, schema1)
True
>>> v.validate({'test': False}, schema1)
False
>>> v.validate({'test': True}, schema2)
False
>>> v.validate({'test': False}, schema2)
False
```

**Comment by funkyfuture** [comment]
i made up this test case, and it works:

```python

def test_issue_428():
    # https://github.com/pyeve/cerberus/issues/428

    def bool_as_string(x):
        return 'true' if x is True else 'false'

    schema = {'test': {
        'coerce': (bool, bool_as_string),
        'type': 'string',
        'regex': '^true$'
    }}
    assert_normalized({'test': 'x'}, {'test': 'true'}, schema)
    assert_success({'test': 'x'}, schema)
```

are you missing that `bool_as_string(bool('ThisShouldActuallyNotConflictWithRegex')) == 'true'`?

**Comment by elben10** [comment]
Yes I guess I'm missing that link. I thought that given input was bool the coercion function would apply. But what you're saying is that the coercion will be used no matter what the input type is?

**Comment by funkyfuture** [comment]
> But what you're saying is that the coercion will be used no matter what the input type is?

do you have other expectations? where do these stem from? does the documentation have a blind spot?

**Comment by elben10** [comment]
I guess I missed the link to custom coercion methods. Thanks for the help.
