### ISSUE TITLE
Schemas with *of-rule do not provide correct path with the BasicErrorHandler

### ISSUE THREAD

**Issue by 14rcole** [pyeve/cerberus#432]
Used Cerberus version / latest commit: 1.1

- [X] I have the capacity to improve the docs when my problem is solved.
- [X] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

Validation errors cease to give any information after an *of-rule

----

#### Bug report / Feature request

Ordinarily, the default validator uses provides information about the offending field and its position within the file when something goes wrong.  For example, it may tell you that the field count, which exists at res_defs[nodes][0][count] must be a number.  However, if the schema has *of-rules, validation errors do not list this information.  For example, instead of the validation errors looking something like this:

```
res_defs[1][count]: value for field 'count' must be of type 'integer'
```

I see something like this

```
	res_defs[0][anyof]: no definitions validate
	res_defs[0][anyof][anyof definition 2]: field '0' could not be recognized within the schema provided
	res_defs[0][anyof][anyof definition 2]: field '0' could not be recognized within the schema provided
	res_defs[0][anyof][anyof definition 2]: field '0' could not be recognized within the schema provided
	res_defs[0][anyof][anyof definition 2]: field '0' could not be recognized within the schema provided
	res_defs[0][anyof][anyof definition 2]: unallowed value 'libvirt_network' for field '0'. Allowed values are: [u'libvirt_storage']
	res_defs[0][anyof][anyof definition 2]: field '0' could not be recognized within the schema provided
	res_defs[0][anyof][anyof definition 2]: field '0' is required
	res_defs[0][anyof][anyof definition 2]: field '0' is required
	res_defs[0][anyof][anyof definition 0]: field '0' could not be recognized within the schema provided
	res_defs[0][anyof][anyof definition 0]: field '0' could not be recognized within the schema provided
	res_defs[0][anyof][anyof definition 0]: field '0' could not be recognized within the schema provided
	res_defs[0][anyof][anyof definition 0]: field '0' could not be recognized within the schema provided
	res_defs[0][anyof][anyof definition 0]: unallowed value 'libvirt_network' for field '0'. Allowed values are: [u'libvirt_node']
	res_defs[0][anyof][anyof definition 0]: field '0' could not be recognized within the schema provided
	res_defs[0][anyof][anyof definition 0]: field '0' is required
	res_defs[0][anyof][anyof definition 0]: field '0' is required
	res_defs[0][anyof][anyof definition 1]: field '0' could not be recognized within the schema provided

```

I don't mind so much that every schema in the anyof block is marked as invalid, but the lack of field names makes it very difficult to debug that actual problem.

**Comment by 14rcole** [comment]
Here are two examples. The first schema does not have an `anyof` block. The first section is the schema, the second is the document used as input, and the third is the output.  The second schema does include an `anyof` block.  It obviously isn't necessary for that particular schema, but I wanted to illustrate the point with two schemas that are as similar as possible (and the results are the same regardless).  Once again, the first second is the schema, the second is the (same) document used as input, and the third is the output.

https://pastebin.com/ACCsvEPU
https://pastebin.com/Gagp0Trn

**Comment by funkyfuture** [comment]
i see, good examples. i guess i'd be the only one to take this. but i do not have much resources atm. i have two proposals: either you investigate whether the `document_…` or `schema_error_tree` may be suitable for what you want to achieve. or you provide a bug fix.

**Comment by funkyfuture** [comment]
i'm not certain whether and if so which milestone to set. @nicolaiarocci do we still maintain the 1.1 branch?

**Comment by nicolaiarocci** [comment]
we don't

**Comment by funkyfuture** [comment]
@14rcole unfortunately the examples you posted vanished. could you please post them here, maybe as attachment if they are too big?

i might be quick with a fix if you instead provided slick test cases.

i'm not sure on this idea: could we postpone this for an 1.2.1 & 1.3.1 or 1.2.2 & 1.3.1 release? we are somewhat overdue with releases and beside the troubles w/ testing against old Python versions there are only this issue and a sorting incoherence across Python versions (which i mostly consider practically irrelevant) scheduled atm.

**Comment by funkyfuture** [comment]
@nicolaiarocci shall we postpone this and bring on the releases?

**Comment by nicolaiarocci** [comment]
yup

**Comment by funkyfuture** [comment]
@nicolaiarocci can you take on with the releases or can i help with preparations?

**Comment by funkyfuture** [comment]
i'm removing the milestone here as long as there's no ample amount of data to reproduce.
