### ISSUE TITLE
Forbidden rule does not support float

### ISSUE THREAD

**Issue by MartyHub** [pyeve/cerberus#436]
The following schema does not work as expected :

```json
{
  "amount": {
    "forbidden": [0],
    "max": 1,
    "min": 0,
    "type": "number",
  }
}
```

because [the forbidden rule](https://github.com/pyeve/cerberus/blob/7d61ac3624d34d5dcb621089e48d91a3d1ee64a7/cerberus/validator.py#L1189) only check for `int` :

```python
Validator().validate(
  {
    "amount": 0.0
  },
  schema
)
```

**Comment by funkyfuture** [comment]
yeah, that last clause should probably be `else` and strings should be tested there too.

**Comment by safaozturk93** [comment]
I'll look at this.
