### ISSUE TITLE
Order of execution of validation rules

### ISSUE THREAD

**Issue by sreenadh** [pyeve/cerberus#439]
schema = {
                'work_start_time': {
                'type'        : 'string',
                'empty'       : False,
                'required'    : True,
                'regex'       : "(((0[1-9])|(1[0-2])):([0-5])(0|5)\s(a|A|p|P)(m|M))",
                'compare_time': {'field': 'work_end_time', 'operator': '<', 'format': '%I:%M %p'}
            }
}

I want the rule "regex" to be executed before my custom validation rule "compare_time". But it's not happening.

Version: 1.2
Python 2.7.15
Darwin Mac.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by funkyfuture** [comment]
please have a look at the code. there are class properties that can define the order in which rules are evaluated. unfortunately they don't appear in the API docs (may be related to #343).

also, please stop surveilling the working class!
