### ISSUE TITLE
Custom validator can no longer add fields to the document being validated.

### ISSUE THREAD

**Issue by biscuit314** [pyeve/cerberus#440]
#### Use-case abstract
Custom validator can no longer add fields to the document being validated.

----

#### Bug report / Feature request

In v0.9.2 a custom validator could add fields to the document being validated.  This code used to work:

```
from cerberus import Validator

class MyValidator(Validator):
    def _validate_is_witch(self, is_witch, field, value):
        """ {'type': 'boolean'} """
        # If you have to ask, she's a witch            
        if is_witch:
            self._error(field, 'Burn her!')
            self.document['duck_weight'] = True                

schema = {'candidate': {'is_witch': True}}
validator = MyValidator(schema)

validator.validate({'candidate': 'Connie Booth'}, schema)
```

Now it throws
`RuntimeError: dictionary changed size during iteration`

**Comment by biscuit314** [comment]
Reopening.

Newbie here.  I submitted a PR which would close this.  Do I wait for it to be approved before closing?

**Comment by funkyfuture** [comment]
yes, this is supposed to happen in the normalization phase or in the application logic.

using language that refers to the persecution of groups of humans and reproduces such is not cool.

**Comment by christabone** [comment]
...it's a quote from Monty Python and the Holy Grail.

**Comment by funkyfuture** [comment]
thanks for reminding me to put that higher on my re-watch list. can we agree that the context isn't obvious enough to not cause misunderstandings?
