### ISSUE TITLE
Cannot pass a dict to self._error()

### ISSUE THREAD

**Issue by biscuit314** [pyeve/cerberus#442]
#### Use-case abstract

Custom validator can no longer call `self._error(field, message)` where `message` is a dict

----

#### Bug report / Feature request

In v0.9.2 a custom validator could pass a dict as the second param to self._error().  This code used to work:

```
from cerberus import Validator

class MyValidator(Validator):
    def _validate_isodd(self, isodd, field, value):
        """ {'type': 'boolean'} """
        if isodd and not bool(value & 1):
            self._error(field, {'message': 'Not an odd number', 'suggestion': 'add or subtract one'})

schema = {'test_field': {'isodd': True}}
validator = MyValidator(schema)
validator.validate({'test_field': 8}, schema)
```

Now it throws 
`AttributeError: 'dict' object has no attribute 'code'`

**Comment by biscuit314** [comment]
Reopening.

Newbie here.  I submitted a PR which would close this.  Do I wait for it to be approved before closing?

**Comment by funkyfuture** [comment]
addidtional data can be passed to `_error` that is then bound to the `info` property of a `Validation` error. have a look at the `BasicErrorHandler` how it can then be used to represent an error.
