### ISSUE TITLE
np.nan is throughout treated as valid entry, a major problem with validator

### ISSUE THREAD

**Issue by swagatam101** [pyeve/cerberus#446]
Version 1.2 

Example code: 

schemaA =  {'type': 'list', 'schema': {'type': 'number', 'min': 0, 'max': 10}}
schema = {'A': schemaA,  'B': {'type': 'list', 'schema': {'type': 'number'}}}

V = cerberus.Validator()
V.validate({'A':[1, 2, np.nan], 'B': [np.nan, 5,  6]}, schema)

Will validate and retain the nans. 
Am I missing something? How can nans not be treated properly in a data validator?

**Comment by funkyfuture** [comment]
> How can nans not be treated properly in a data validator?

because they are not a Python builtin and you need to [extend](http://docs.python-cerberus.org/en/stable/customize.html#custom-data-types) the semantics of the `number` constraint or define a custom one.
