### ISSUE TITLE
Usage of allowed and nullable params

### ISSUE THREAD

**Issue by mishgu** [pyeve/cerberus#454]
I'm have a issues when use allowed and nullable params
----
#### Use-case abstract
```
 schemas = [
    {'role': {'type': 'string', 'allowed': ['agent', 'client', 'supplier']}},
    {'role': {'type': 'string', 'allowed': ['agent', 'client', 'supplier', None]}},
    {'role': {'type': 'string', 'allowed': ['agent', 'client', 'supplier'], 'nullable': True}},
    {'role': {'type': 'string', 'allowed': ['agent', 'client', 'supplier', None], 'nullable': True}},
    {'role': {'type': 'string', 'nullable': True}},
]
data = [
    {'role': 'agent'},
    {'role': None},
]
```
Output from cerberus
```
Version - 1.2
Schema # 	   Data
   1		True  False  
   2		True  False  
   3		True  False  
   4		True  True  
   5		True  True  
```
----
```
Version - 1.1
Schema # 	   Data
   1		True  False  
   2		True  False  
   3		True  True  
   4		True  True  
   5		True  True  
```
#### Bug report / Feature request
As we can see in v1.2 have different ouput with **nullable** param (3td schema). It looks like a bug
In my oppinion v1.1 working more properly

**Comment by funkyfuture** [comment]
see also #393 and #400. it would be helpful if you researched with `git bisect` which commit changed the behaviour. would you prefer that a positively defined `nullable` implies `None` to be included in `allowed`'s constraints?

**Comment by cpforbes** [comment]
This appears to be related to #373

**Comment by cpforbes** [comment]
After looking at the old code a bit more it seems that previously all other rules were skipped after the nullable rule if the field was null.

https://github.com/pyeve/cerberus/blob/1018ac8dfe8f8dd1a247dd33b5c3e1d182d868a6/cerberus/validator.py#L864

**Comment by funkyfuture** [comment]
no, on the contrary, no rules were skipped at all.
