### ISSUE TITLE
`empty` doesn't work with custom rules

### ISSUE THREAD

**Issue by solo-framework** [pyeve/cerberus#461]
Used Cerberus : 1.2

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

Validator doesn't skip checking custom rules if value is empty and `empty` rule is set
I expect the validator will not execute the custom rule if the value is empty

----

#### Bug report / Feature request

There is custome rule:

```
class MyValidator(Validator):
		def _validate_myrule(self, myrule, field, value):
			""" Test the oddity of a value.
			
			{'type': 'boolean'}
			"""
			if myrule != "myrule":
				self._error(field, "Must be 'myrule' string")
```
Data & schema

```
schema = {'num': {'type': 'string',
	                   'empty': True,
	                   'myrule': True,
	                   'required': False
	                   }}
document = {'num': ''}
v = MyValidator(schema)
v.validate(document)
```

output is
```
{'num': ['Must be 'myrule' string']}
```

**Comment by funkyfuture** [comment]
you'd either have to override the [_validate_empty](https://github.com/pyeve/cerberus/blob/master/cerberus/validator.py#L1177) method to include your rule to be dropped or you could submit a patch that makes the rules to be dropped configurable with a class attribute.

**Comment by nicolaiarocci** [comment]
@funkyfuture please, go ahead with the review/rebase/merge of pull requests. Just make sure changelog is costantly updated to reflect changes/new things. Possibly, ensure the git log is as clean as possible. It will still be some time before I can get back at full speed, and I do not wan to slow down the project.

**Comment by funkyfuture** [comment]
i'm closing this, anyone who implements the proposed class attribute may use this issue as reference.
