### ISSUE TITLE
`validator:` rule as string does not work

### ISSUE THREAD

**Issue by jeking3** [pyeve/cerberus#466]
Used Cerberus version / latest commit: …

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

I want to make a subclass of cerberus.Validator has to work with a schema that is read in from a file, and that validates the contents of a field using a custom validator.  Given the schema is read in from a file, I cannot specify the field validator as a `callable`.

----

#### Bug report / Feature request

The documentation states that a field validator rule can be either a `callable`, or `string`, or `list` containing either.  The `callable` seems to work okay, however using a `string` yields:

```
cerberus.schema.SchemaError: 
    {'size': [{'validator': ['none or more than one rule validate', 
            {'oneof definition 0': ['must be of callable type'], 
             'oneof definition 1': ['must be of list type'], 
             'oneof definition 2': ['unallowed value size_func']}]}]}
```

This happens with cerberus 1.2 and with master.  Note the "unallowed value size_func" which is strange, because the cerberus _validate_validator docstring schema appears to allow for this case.

Example:
```
#!/usr/bin/env python3
import humanfriendly
import sys
from cerberus import Validator

class CustomValidator(Validator):
    def _validate_size_func(self, field, value, error):
        """ {'type': ['integer', 'string']} """
        try:
            humanfriendly.parse_size(value, binary=True)
        except humanfriendly.InvalidSize:
            error(field, 'invalid size')

schema = {
    'size': {
        'validator': 'size_func'
    }
}

uut = CustomValidator(schema=schema)
if not uut.validate({'size': '10mb'}):
    sys.exit(1)
print('ok')
```

The example in the documentation has a string with a space in it, `prime number`, and I'm not sure how that would be mapped to a class `_validate_` method.  I suppose a workaround to this case is to use a rule instead of a validator:
```
schema = {
    'size': {
        'type': ['integer', 'string'],
        'size': True
    }
}
```

**Comment by funkyfuture** [comment]
> using a custom validator

i'm not sure whether it's about custom validator or a custom rule which your example shows considering the method name but not by its signature.

**Comment by jeking3** [comment]
This is about using a custom validator in a subclass.  See:

http://docs.python-cerberus.org/en/stable/validation-rules.html#validator

I'm able to make it work using a custom rule just fine, but I could not make it work using a `validator:` field with a string as the argument, which by documentation (and the code, from the looks of it) should call a `_validate_<string>` class method to run the custom validation.  Perhaps I did something silly, but I spent enough time on it today to satisfy myself it is a bug.  If you specify a string there, cerberus fails with a SchemaError.

**Comment by funkyfuture** [comment]
a custom validator is prefixed with `_validator_` (1.2) respectively `_check_with_` (coming in 1.3), see [here](http://docs.python-cerberus.org/en/stable/customize.html#custom-validators). i would recommend to use the renamed `check_with` rule as it should avoid confusion of concepts.

**Comment by funkyfuture** [comment]
can we close this issue?

**Comment by jeking3** [comment]
Sure, you can, but I don't think the issue is resolved.  I ended up using a new custom rule instead of a validator because the validator logic is broken as reported.

**Comment by funkyfuture** [comment]
i'm not sure where our misunderstanding is stemming from.

maybe i wasn't clear enough:
1) in your initial example you use a method name for a *rule*.
2) while at the same time you use the signature of a `check_with` method. but a rule takes the constraint, the field and the value as arguments.

is that still your code?

**Comment by jeking3** [comment]
Got it now, and I see why you renamed the validator rule to check_with, just to avoid this confusion.  Thanks for the help.

**Comment by jeking3** [comment]
This works with cerberus 1.2:
```
#!/usr/bin/env python3
import humanfriendly
import sys
from cerberus import Validator

class CustomValidator(Validator):
    def _validator_size_func(self, field, value):
        """ {'type': ['integer', 'string']} """
        try:
            humanfriendly.parse_size(value, binary=True)
        except humanfriendly.InvalidSize:
            error(field, 'invalid size')

schema = {
    'size': {
        'validator': 'size_func'
    }
}

uut = CustomValidator(schema=schema)
if not uut.validate({'size': '10mb'}):
    sys.exit(1)
print('ok')
```
