### ISSUE TITLE
Forcing endswith(‘$’) for regex blocks some scenarios

### ISSUE THREAD

**Issue by Nemesis7** [pyeve/cerberus#474]
Used Cerberus version / latest commit: 1.2

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [x] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

By forcing the dollar sign at the end of a regular expression, a negative lookbehind scenario will not work, example: http://www.learningaboutelectronics.com/Articles/Negative-look-behind-regular-expression-in-Python.php

By doung this, you’ll never detect if there are violations in the rest of the string.

#### Bug report / Feature request
Remove the endswith(‘$’) requirement from regex validation.

**Comment by Nemesis7** [comment]
Personal example: I want to reject strings that have dots in them, except when there are preceded with 'jr', 'sr' or 'st', which I found this regex for: `(?<!jr|sr|st)\.*` This results the dots that don't have these prefixes being detected. But with Cerberus this won't work as it will always look for dots at the end of the string ($).

**Comment by Nemesis7** [comment]
Changing the _validate_regex to the following solves the problem, requiring the $ to be set explicitly when defining rules:

`    def _validate_regex(self, pattern, field, value):
        """ {'type': 'string'} """
        if not isinstance(value, _str_type):
            return
        re_obj = re.compile(pattern)
        if not re_obj.search(value):
            self._error(field, errors.REGEX_MISMATCH)`

**Comment by funkyfuture** [comment]
how does the test suite behave in that case?

regarding your use-case, here's a rhetorical, ironic question: with a negative lookbehind you multiply the inital problem count by three, don't you?

**Comment by Nemesis7** [comment]
Hi @funkyfuture,

I can't somehow run pytest for `test_validation.py`, sorry.
In my use case I want to detect all dots in the string that aren't preceded by those 3 prefixes. So maybe it is inefficient, but I haven't found a working alternative for my scenario.

**Comment by funkyfuture** [comment]
> I can't somehow run pytest for test_validation.py, sorry.

could you please elaborate?

> but I haven't found a working alternative for my scenario.

there's always the `check_with` (formerly `validator`) rule to deal with special cases. it's probably more expressive than a regex as well.

**Comment by Nemesis7** [comment]
> could you please elaborate?
Yes, I have pytest-django which expect a config file, and I don't have time to fix that now, I can check later.
> there's always the check_with (formerly validator) rule to deal with special cases. it's probably more expressive than a regex as well.
Ah, I didn't know this, I haven't seen any documentation, I will experiment with this.

**Comment by Nemesis7** [comment]
@funkyfuture Please close this issue, as I have this working with the following regex: `^.*(?<!jr|sr|st)\..*$`. But please provide an example for check_with. Thanks!
