### ISSUE TITLE
Using min and max with datetimes

### ISSUE THREAD

**Issue by tallesl** [pyeve/cerberus#476]
Is it possible to use the `min` and `max` validation rules against `datetime` datatype?

I imagine this would be fairly trivial to support out of the box, but eve documentation indicates that there isn't:

> Minimum and maximum values allowed for `integer`, `float` and `number` types.

**Comment by funkyfuture** [comment]
[Cerberus' docs](https://docs.python-cerberus.org/en/stable/validation-rules.html#min-max) are clear on that. please open issues regarding Eve in the corresponding repository.
