### ISSUE TITLE
No validation schema is defined for the arguments

### ISSUE THREAD

**Issue by tallesl** [pyeve/cerberus#477]
Why if I remove the docstring in the [docs example](http://docs.python-cerberus.org/en/stable/customize.html#custom-rules) I got the warning below?

> UserWarning: No validation schema is defined for the arguments of rule 'isodd'

(looks like it's coming from [here](https://github.com/pyeve/cerberus/blob/eb1012f4d9200b0e662faed9cc3132f616445fcc/cerberus/validator.py#L1608))

[On eve documentation the docstring is absent by the way](https://docs.python-eve.org/en/stable/validation.html#custom-validation-rules).

**Comment by funkyfuture** [comment]
it is explained in the last paragraph of the section you're referring to. feel free to open a pr w/ improvements.

**Comment by milahu** [comment]
```py
class CustomValidator(cerberus.Validator):
  def _validate_iscustomvalid(self, iscustomvalid, field, value):

    "{'type': 'boolean'}" # <-- this was missing: schema of rule argument

    if iscustomvalid and re.match(r'^\d{4}$', value) == None:
      self._error(field, 'Must have format [0-9]{4}')

schema = {
  'somefield': {
    'iscustomvalid': True # <-- rule argument: {'type': 'boolean'}
  },
}
```

**Comment by shqear93** [comment]
same here

**Comment by artur-cesar** [comment]
Same here too

**Comment by milahu** [comment]
> ```python
> class CustomValidator(cerberus.Validator):
>   def _validate_iscustomvalid(self, iscustomvalid, field, value):
> 
>     "{'type': 'boolean'}" # <-- this was missing: schema of rule argument
> ```

**Comment by shqear93** [comment]
## My Validator:

```python

class ExtendedValidator(Validator):
    def _validate_matches_resource_name(self, matches_resource_name, field, value):
        if matches_resource_name:
            ...implementation

```

## Error

```
../site-packages/cerberus/validator.py:1666: UserWarning: No validation schema is defined for the arguments of rule 'matches_resource_name'
  warn(
Checking file: '../users/user--serviceyaml'
--------------------------------------------------
```

It also exist with error code 1:

## Reason:

Schema of rule argument was missing from the method docs

## Solution:


```python
class ExtendedValidator(Validator):
    def _validate_matches_resource_name(self, matches_resource_name, field, value):
        """
        Test the custom 'matches_resource_name' rule.

        This method checks blablabla...

        The rule's arguments are validated against this schema:
            {'type': 'boolean'}
        """
        if matches_resource_name:
            ...implementation
```
