### ISSUE TITLE
*of_check_with results in SchemaError due to unknown rule

### ISSUE THREAD

**Issue by jasongraham** [pyeve/cerberus#484]
Used Cerberus version / latest commit: **1.3**

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

I'm attempting to replace the usage of `validator`s within my schemas with `check_with`.

I've run into a problem trying to use `*of_check_with`.

My previous usage of `*of_validator` did indeed work just fine, and I would like to continue using this pattern.

----

#### Bug report / Feature request

Attempting to use `check-with` in place of `validator` within an [`*of` typesaver](http://docs.python-cerberus.org/en/stable/validation-rules.html#of-rules-typesaver) structure results in a `SchemaError` being raised.

Example contents of `test.py`
```python
import cerberus

# Arbitrary dummy validators
def foo(field, value, error):
    ...

def bar(field, value, error):
    ...

schema = {
    "a": {
        # Also fails with oneof, allof, noneof
        # replacing with *of_validator works
        "anyof_check_with": [foo, bar]
    }
}

cerberus.Validator(schema)
```

Result: of running `python test.py`
```python
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    cerberus.Validator(schema)
  File .../python3.7/site-packages/cerberus/validator.py", line 181, in __init__
    self.schema = kwargs.get('schema', None)
  File ".../python3.7/site-packages/cerberus/validator.py", line 562, in schema
    self._schema = DefinitionSchema(self, schema)
  File ".../python3.7/site-packages/cerberus/schema.py", line 76, in __init__
    self.validate(schema)
  File ".../python3.7/site-packages/cerberus/schema.py", line 247, in validate
    self._validate(schema)
  File ".../python3.7/site-packages/cerberus/schema.py", line 263, in _validate
    raise SchemaError(self.schema_validator.errors)
cerberus.schema.SchemaError: {'a': [{'anyof_check_with': ['unknown rule']}]}
```

**Comment by funkyfuture** [comment]
thanks for reporting!
