### ISSUE TITLE
Deprecation with py37, Cerberus 1.3

### ISSUE THREAD

**Issue by jeking3** [pyeve/cerberus#486]
.tox/py37/lib/python3.7/site-packages/cerberus/errors.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
    from collections import defaultdict, namedtuple, MutableMapping
```

Used Cerberus version / latest commit:1.3

- [ ] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

----

**Comment by funkyfuture** [comment]
true. is this appearing when you test an application or when you run  the test suite? i don't see this warning when i do the latter with 3.7.

are you providing a fix in the next hour or so?

**Comment by jeking3** [comment]
This is part of running a test suite with pytest.  I have silenced it through pytest.ini filterwarnings for now.  I don't have a code fix queued up for it right now.

**Comment by funkyfuture** [comment]
sorry, my question wasn't clear: are you running the test suite of Cerberus or of an application using it?

**Comment by jeking3** [comment]
Sorry, it is of an application using cerberus.

**Comment by funkyfuture** [comment]
okay, thanks!
