### ISSUE TITLE
Python 3.10 support?

### ISSUE THREAD

**Issue by andreymal** [pyeve/cerberus#488]
```
>>> import sys
>>> sys.version_info = (3, 10, 0)
>>> import cerberus.platform
>>> print(cerberus.platform.PYTHON_VERSION)
4.0
```

wat.

Not sure if Python 3.10 will exist in the future (Python 4.0 will probably be made), but I think this is a bad idea to use a float for the `PYTHON_VERSION` variable.

**Comment by funkyfuture** [comment]
good catch. but i doubt this piece of code will sustain 'til we get there. oh, [we won't get there](https://www.reddit.com/r/Python/comments/7zvyhx/pep_563_mentions_python_40_whats_going_on/dur5x0d/) (i remember that there were other sources circulating this info). a patch would be accepted anyway.
