### ISSUE TITLE
Unable to validate dict

### ISSUE THREAD

**Issue by kamikaze** [pyeve/cerberus#498]
Unable to validate dict with random keys like this:

```python
document = {
    'random_key_1': {},
    'random_key_2': {},
}
```

How do I write rules for such dict? Keys are completely random strings. All the examples I found are designed for dictionaries with strict key names on top-level.

**Comment by Flargebla** [comment]
Are you trying to validate the keys of this dict, or the values? If you just care about the values, I would just feed each value into a Validator with a relevant schema. 

You should be able to do something like dynamically build a schema once you know the keys as well. For example, if my keys are random strings between "1" and "10", I could build a schema once I see the dict that I am trying to validate using code similar to this:

```python
# Assume we get a dict looking like this:
d = {
    "6": {"key_one": "value_one"},
    "2": {"key_one": [1, 2, 3]}
}

schema = {}

for k in d.keys():
    schema[k] = <some_predefined_schema_for_key_k>

v = Validator(schema)
v.validate(d)
```

Not sure about your specific use-case, but I hope this helped.

**Comment by funkyfuture** [comment]
i'm not keen on interacting with people that are using disgusting avatars.

**Comment by kamikaze** [comment]
> 
> 
> i'm not keen on interacting with people that are using disgusting avatars.

What is so disgusting in my avatar? Any problems with that? Or maybe with your interpretation and thoughts?
