### ISSUE TITLE
Willing to add more examples for Validation Rules 

### ISSUE THREAD

**Issue by vipulgupta2048** [pyeve/cerberus#500]
Hello there, 
I am Vipul Gupta, and I am participating in [Google Summer of Code 2019](https://mixstersite.wordpress.com/gsoc/). Cerberus is helping me out quite a lot in my project. Hence, I think what better way to help the project than to contribute back to it. I am an experienced freelance documentation writer. I kinda referred a lot to Validation Rules pages for examples as a reference regarding various features of Cerberus. I see there are fewer examples of some rules. 

Now, I know there is no need for examples of every single rule out there, but as a beginner, I think it certainly helps people when they can refer to something. I have already made several examples of my own when I was writing tests for my use-case. And it would be my honor to contribute back to this amazing package in whatever way possible. 

I also understand if the reason not to go ahead with this is to `not` bloat up the docs. I get that :smile:, but if you feel there is some need for them. I can post the examples on my blog (Check out - http://Mixster.live)

Thank you for all the work being done with Cerberus.

**Comment by funkyfuture** [comment]
ciao Vipul, nice to hear that Cerberus provided you a satsifying development experience. you are right, the docs have grown as the features did, and as a result they are inconsistent to a degree.

do you have a roundabout number on how much examples would be added for how much rules? with that, i think we can find a way how to proceed best.

i'm assuming that the examples refer to the `1.3` release series, right?

oh, and don't worry to throw stuff out when you have a useful replacement.

**Comment by vipulgupta2048** [comment]
Hi @funkyfuture, to be honest, I am not sure of the release series iterations or what's new or about a roundabout number of examples that I am thinking to add. 

I was just looking through the validation rules the other day, saw no examples for anyof, allof, max and minlength. I knew how they worked, so with a little help from the source code, and my previous experience with Schematics and JSONSchema. I built my cases for the project. Then, it came to mind that there is a need to add to on to the docs (I freelance to write docs - so I identify things missing)

I think I can proceed ahead if there is a list of all validation rules, I can form up examples for every one of them if possible, file a PR. How does that sound?

**Comment by funkyfuture** [comment]
a list of all validation rules is included in the doc's table of contents at https://docs.python-cerberus.org/

sure, just kick off a pr.

**Comment by funkyfuture** [comment]
i'm closing this, just open a pr when you have somthing.

**Comment by vipulgupta2048** [comment]
No worries, I am still working on it, I will make a PR soon. Thanks,

**Comment by vipulgupta2048** [comment]
Hey @funkyfuture, I was recently working on this and on another run-through I found almost all of the validation rules have their examples, and descriptions covered. 
Still, I added an example to max length and min length. Should I make PR?
Also, wanted to ask are there any examples that I could be adding that you think could improve. Let me know
