### ISSUE TITLE
datetime validation

### ISSUE THREAD

**Issue by rmlopes** [pyeve/cerberus#506]
Using Cerberus version 1.3.1 (also 1.2):

- [X] I have the capacity to improve the docs when my problem is solved.
- [X] I have the capacity to submit a patch when a bug is identified.

- [X] My question does not concern a practical use-case that I can't figure out
      to solve.

#### Use-case abstract

Detected using Eve, default `DATE_FORMAT` configuration.

#### Bug report

Should accept default ISO-8601 datetime strings: "2017-01-01T00:00:00.000Z". Validation always fails.

```
from cerberus import Validator
schema = {"mydate": {"type":"datetime"}}
document = {"mydate": "2019-01-01T00:00:00.000Z"}
v = Validator(schema)
v.validate(document)
# False
v.errors
# {'mydate': ['must be of datetime type']}
```

Note: The default format in Eve is "%a, %d %b %Y %H:%M:%S GMT". This is not validated by Cerberus as well. What should the format be?

**Comment by funkyfuture** [comment]
please have a look at the [types mapping](https://docs.python-cerberus.org/en/stable/validation-rules.html#type). for Eve-specific issues, open one on that issue tracker.

**Comment by rmlopes** [comment]
Thanks  @funkyfuture.
