### ISSUE TITLE
Unable to validate anyof schema

### ISSUE THREAD

**Issue by purna777** [pyeve/cerberus#510]
```
{
  "offers": {
    "type": "list",
    "schema": {
      "type": "dict",
      "oneof":[{
      "schema": {
        "random1": {
          "type": "float",
          "empty": False
        },
        "random2": {
          "type": "float",
          "empty": False     
        }}}],
        "schema":{
        "offerId": {
          "type": "string",
          "required": True,
          "empty": False
        },
        "frequency": {
          "type": "string",
          "empty": False
        },
        "action": {
          "type": "string",
          "required": True,
          "empty": False
        }
      }
    }
}
```
I'm trying to validate the `oneof` schema and it is giving `True` when both `random1` and `random2` are not in the request. even i have tried with all other `of-rules`.can you help me with this?

**Comment by purna777** [comment]
I'm looking for a schema where

> if i pass both fields in schema it should pass, if i have only one among the two it should pass, if i haven't pass both it should fail.

**Comment by funkyfuture** [comment]
this question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/cerberus), you might get an answer there when you provide more context to your problem and what you've tried so far.
