### ISSUE TITLE
TypeError when using cerberus for recursive data validation

### ISSUE THREAD

**Issue by bertusk** [pyeve/cerberus#513]
I'm using Cerberus 1.3.1 and I'm getting this error when validating a recursive data structure.
Here's some example code that triggers the error:

```python
binop = {
    "binop": {
        "type": "dict",
        "schema": {
            "left": {
                "schema": "expr",
                "required": True
            },
            "right": {
                "schema": "expr",
                "required": True
            },
            "operator": {
                "type": "string",
                "required": True
            },
        },
    }
}

var = {
    "variable": {
        "type": "dict",
        "schema": {
            "name": {
                "type": "string"
            }
        }
    }
}

expr = {
    "expr": {
        "type": "dict",
        "schema": {
            "anyof": [
                {"schema": var},
                {"schema": binop}
            ]
        }
    }
}

cerberus.schema_registry.add('expr', expr)
schema = {"expressions": {"type": "list", "schema": "expr"}}

v = cerberus.Validator(schema)

doc = {
    "expressions": [
        {
            "expr": {
                "binop": {
                    "left": {"expr": {"variable": {"name": "var1"}}},
                    "right": {"expr": {"variable": {"name": "var2"}}},
                    "operator": "+"
                }
            }
        },
        {"expr": {"variable": {"name": "var3"}}},
        {"expr": {"variable": {"name": "var4"}}}
    ]
}
print(v.validate(doc))

```
When I run this code I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 71, in <module>
    print(v.validate(doc))
  File ".venv/lib/python3.6/site-packages/cerberus/validator.py", line 990, in validate
    self.__normalize_mapping(self.document, self.schema)
  File ".venv/lib/python3.6/site-packages/cerberus/validator.py", line 671, in __normalize_mapping
    self.__normalize_containers(mapping, schema)
  File ".venv/lib/python3.6/site-packages/cerberus/validator.py", line 757, in __normalize_containers
    self.__normalize_sequence_per_schema(field, mapping, schema)
  File ".venv/lib/python3.6/site-packages/cerberus/validator.py", line 826, in __normalize_sequence_per_schema
    result = validator.normalized(document, always_return_document=True)
  File ".venv/lib/python3.6/site-packages/cerberus/validator.py", line 646, in normalized
    self.__normalize_mapping(self.document, self.schema)
  File ".venv/lib/python3.6/site-packages/cerberus/validator.py", line 660, in __normalize_mapping
    self.__normalize_rename_fields(mapping, schema)
  File ".venv/lib/python3.6/site-packages/cerberus/validator.py", line 864, in __normalize_rename_fields
    self._normalize_rename(mapping, schema, field)
  File ".venv/lib/python3.6/site-packages/cerberus/validator.py", line 877, in _normalize_rename
    if 'rename' in schema[field]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by funkyfuture** [comment]
ciao, that somehow rings a bell, but i can't find anything related ad hoc.

i'm setting the 1.3.2 milestone (supposed to be released soonish) for now though the report is still unconfirmed as bug.

what you can do to help:

- try it with the current `1.3.x` branch
- reduce your example as much as possible
- find and fix the error in you code or Cerberus

i can't say atm when i will have the time to look at it.

oh, that part in the `expr` symbol looks weird: `schema` -> `anyof` -> `schema`

**Comment by bertusk** [comment]
Hi Frank,

Thanks for the response.  I've simplified my example here (and also removed the weird schema -> anyof -> schema part):

```python
body = {
    "body": {
        "type": "list",
        "schema": {
            "anyof": [
                {
                    "item": {
                        "name": {"type": "string"},
                        "body": {
                            "type": "list",
                            "schema": {
                                "schema": "body",
                                "required": True
                            }
                        }
                    }
                },
            ]
        }
    }
}

cerberus.schema_registry.add("body", body)
schema = {"document": {"schema": "body"}}

v = cerberus.Validator(schema)

doc = {
    "document": {
        "body": [{
            "item": {
                "name": "test",
                "body": []
            }
        }]
    }
}
print(v.validate(doc))
```
This example still captures what I want to do.  Essentially, I want to have a list ("body") of dictionaries with various schemas and some recursive (containing more body elements).  So the schema is self referencing since an item can contain a body which may contain items with body fields.  

However, when running the code in the above example I get a nonsensical SchemaError since it claims "anyof" must be of type dict.

> Traceback (most recent call last):
  File "test2.py", line 33, in <module>
    v = cerberus.Validator(schema)
  File ".venv/lib/python3.6/site-packages/cerberus/validator.py", line 181, in __init__
    self.schema = kwargs.get('schema', None)
  File ".venv/lib/python3.6/site-packages/cerberus/validator.py", line 562, in schema
    self._schema = DefinitionSchema(self, schema)
  File ".venv/lib/python3.6/site-packages/cerberus/schema.py", line 82, in __init__
    self.validate(schema)
  File ".venv/lib/python3.6/site-packages/cerberus/schema.py", line 259, in validate
    self._validate(schema)
  File ".venv/lib/python3.6/site-packages/cerberus/schema.py", line 275, in _validate
    raise SchemaError(self.schema_validator.errors)
cerberus.schema.SchemaError: {'document': [{'schema': ['no definitions validate', {'anyof definition 0': [{'body': [{'schema': ['no definitions validate', {'anyof definition 0': [{'anyof': ['must be of dict type']}], 'anyof definition 1': [{'anyof': [{'item': ['unknown rule']}]}]}]}]}], 'anyof definition 1': ['Rules set definition body not found.']}]}]}

Anyway, I'll see if I can get time to try this against the 1.3.x branch.

**Comment by funkyfuture** [comment]
yeah, i don't think that `schema` -> `anyof` -> `items` makes sense.

**Comment by funkyfuture** [comment]
that is probably what you should consider: `{'item': ['unknown rule']}`.

**Comment by marccarre** [comment]
@bertusk, did you eventually find a solution to your problem? 🤔 
If so, would you mind sharing your solution? 🙏🏻😊 
(Asking as I face [a similar problem](https://stackoverflow.com/questions/78417363/validate-a-recursive-data-structure-e-g-tree-using-python-cerberus-v1-3-5).)

**Comment by bertusk** [comment]
@marccarre, I ended up using https://pypi.org/project/jsonschema/ which validates json, which was OK for my use case.
