### ISSUE TITLE
Check with rule doesn't work as expected

### ISSUE THREAD

**Issue by BinarSkugga** [pyeve/cerberus#514]
Hi and thanks for the awesome library !

So I'm using the latest version of Cerberus on pip and I have a weird problem where check_with doesn't seem to be scoped (if that makes sense). Basically I'm using this schema:

```python
{
  'id': {'type': 'integer', 'min': 1},
  'name': {'type': 'string', 'empty': False, 'required': False, 'maxlength': 127},
  'elements': {'type': 'list', 'required': False, 'minlength': 1, 'check_with': 'elements',
    'schema': {
      'type': 'dict',
      'schema': {
        'id': {'type': 'integer', 'min': 1},
        'order': {'type': 'integer', 'min': 0}
        'duration': {'type': 'float', 'min': 0, 'max': 1},
      }
    }
  }
}
```
With the following validator:
```python
class CustomValidator(Validator):
    def _check_with_elements(self, field, value):
		# Scale to 1000 to eliminate floating point errors
        durations = [int(e['duration'] * 1000) for e in value if 'duration' in e]
        orders = [set(e['order'] for e in value if 'order' in e)]

        if reduce(lambda x, y: x + y, durations, 0) != 1000:
            self._error(field, 'The sum of all durations needs to be equal to 1.')
        if len(value) != len(orders):
            self._error(field, 'Each order value must be uniquely assigned.')
```
So basically the sum of all the durations of every elements should alway be equal to 1. I'm multiplying by 1000 to limit the input to 3 decimal and avoid floating point errors. Everythings looks okay to me but when validating the following document I get the 'The sum of all durations needs to be equal to 1.' error.
```python
{
  'id': 12, 
  'name': 'test_edit_body_duration4', 
  'elements': [
    {'id': 900, 'duration': 0.5, 'order': 1},
    {'id': 901, 'duration': 0.5, 'order': 2}
  ]
}
```
I have been working on this for hours and I can't understand what is wrong with it :/. My first guess was that some old errors were re-thrown or something. At runtime, durations is [500, 500] and the result is 1000, the step-by-step debug event skip the error line.

Thanks in advance !

*EDIT:* I'm executing this in automated tests (unittest) if that can help.

**Comment by funkyfuture** [comment]
what is `e` in your example? wouldn't using `sum` be simpler? 

> when validating the following document I get the 'The sum of all durations needs to be equal to 1.' error.

> the step-by-step debug event skip the error line.

you may add a failing `assert` statement before the `_error` method is called to get a traceback.

**Comment by BinarSkugga** [comment]
> what is `e` in your example? wouldn't using `sum` be simpler?

That is from the list expression, its every element of the list like a map, I didn't know sum existed, I'll try that.

Thanks for the reply !

**Comment by BinarSkugga** [comment]
It was because of some logic errors. First the reduce didn't worka as i needed and was still getting rounding errors. The order would also fail because of how i was trying to parse it into a list. In brief, everything is good, thanks !
