### ISSUE TITLE
Could someone provide data sets and accompanying schema(s) for benchmarking?

### ISSUE THREAD

**Issue by funkyfuture** [pyeve/cerberus#517]
as i'm planning to implement different changes that could and would have different outcomes regarding the time that is spent for the preparation of a schema and the actual processing of a document, i'd like to add benchmarking tests to the test suite. the tests currently do not reflect the usual usage well as a schema is used only a few times at most, while real-world solutions usually employ one schema for thousands and more of documents.

before i create a set of supposed real-world documents, i'd like to aks the community whether someone can provide a larger amount of documents that have been processed against a single schema. the data set must not contain any sensible data, we could of course pseudonimize such sets. whether or not the documents would succeed a validation isn't of much interest, but the documents should all roughly match the schema's structure.

**Comment by msotnikov** [comment]
Hope this helps https://repl.it/repls/StarchyDentalRoute
I can provide more if you need.

**Comment by funkyfuture** [comment]
yes, this looks intersting. how much datasets could you provide?

**Comment by msotnikov** [comment]
I have a lot. But this require some manual work. I can provide another 20k valid documents and about 1k invalid easyly.

**Comment by funkyfuture** [comment]
that'd be absoulutely sufficient. could you prepare a module that works [like this](https://github.com/pyeve/cerberus/blob/master/cerberus/benchmarks/test_overall_performance.py). without the document generation, of course.

**Comment by msotnikov** [comment]
Here https://repl.it/join/pclscznk-mikhailsotnikov
Code must to be reviewed, I think.

![image](https://user-images.githubusercontent.com/16710810/83967978-6a65b080-a8ce-11ea-81c8-e8e26bfa3b83.png)

**Comment by funkyfuture** [comment]
could you please open a pull request here? there are handy review features here.

**Comment by msotnikov** [comment]
> could you please open a pull request here? there are handy review features here.

https://github.com/pyeve/cerberus/pull/551
