### ISSUE TITLE
v1.3.x BareValidator has an inconsistent `type_mapping`

### ISSUE THREAD

**Issue by sonnysideup** [pyeve/cerberus#518]
Using the HEAD of Cerberus **v1.3.x** branch: https://github.com/pyeve/cerberus/commit/c41b0311dd5bcff5672e4600f2d30545280a71e1

- [X] I have the capacity to improve the docs when my problem is solved.
- [X] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Bug report / Feature request

`cerberus.validator.BareValidator.types_mapping` uses tuples for all `TypeDefinition.included_types` expect for one:

https://github.com/pyeve/cerberus/blob/c41b0311dd5bcff5672e4600f2d30545280a71e1/cerberus/validator.py#L133

This is a simple typo, right?

**Comment by funkyfuture** [comment]
yes, it's a typo. a fix would be merged. out of curiosity: how does it affect you?

**Comment by sonnysideup** [comment]
@funkyfuture Our team currently uses Voluptuous for validation and dataclasses for configuration types. 

I'm building out a new validation scheme using cerberus and trying to migrate off of voluptuous using the `dataclasses.field.metadata` to abstract the details of both libraries during our transition (huge, multi-step migration). I'm use `cerberus.validator.BareValidator.types_mapping` to convert Voluptuous-style types (e.g. `str`, `int`, `list`) into cerberus string-based type descriptors.

**Comment by funkyfuture** [comment]
done w/ b2d438950c3b79a0bbb9030e63221573aaef06f0
