### ISSUE TITLE
`keysrules` isn't working with `type: list`

### ISSUE THREAD

**Issue by KyleKing** [pyeve/cerberus#521]
Cerberus version: `1.3.2` (latest)

- [X] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.
- [X] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Summary and Code Example

Should `keysrules` work with type `list`?

In the below example, the expected result is for `val.validate(document, schema_keysrules)` to return True (no errors)

```py
from cerberus import Validator

schema_schema = {
    'key1': {
        'type': 'dict',
        'schema': {
            '01': {
                'type': 'list',
                'schema': {'type': 'float'},
            },
            '101': {
                'type': 'list',
                'schema': {'type': 'float'},
            },
        },
    },
}
schema_keysrules = {
    'key1': {
        'type': 'dict',
        'keysrules': {
            'regex': r'[0-9]{2,3}',
            'type': 'list',
            'schema': {'type': 'float'},
        },
    },
}

document = {
    'key1': {
        '01': [10.0, 10.0],
        '101': [0.1, 10.0],
        '999': [1.2, 34.5],
    },
}

val = Validator()

# Try with standard schema
print(val.validate(document, schema_schema))
print(val.errors)

# Try with keysrules
print(val.validate(document, schema_keysrules))
print(val.errors)
```

```sh
val.validate(document, schema_schema): False
val.errors: {'key1': [{'999': ['unknown field']}]}

val.validate(document, schema_keysrules): False
val.errors: {'key1': [{'01': ['must be of list type'],
                  '101': ['must be of list type'],
                  '999': ['must be of list type']}]}
```

**Comment by funkyfuture** [comment]
since keys must be hashables, and lists aren't, no.

but i must admit that i don't understand what your examples have to do with the question. anyway, usage questions are better asked on StackOverflow.

**Comment by KyleKing** [comment]
Thanks! I thought this was a bug in `keysrules`, but it was user error. I should have used `valuesrules` since the `keysrules` `regex` is applied to the key and not the value
