### ISSUE TITLE
how to add multi lingual and custom errors ?

### ISSUE THREAD

**Issue by javadasoodeh** [pyeve/cerberus#523]
Used Cerberus version / latest commit: …

- [ ] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

----

**Comment by javadasoodeh** [comment]
I found:

`from pprint import pformat, pprint

from cerberus import Validator, errors
from cerberus.errors import BaseErrorHandler, encode_unicode
from copy import copy, deepcopy
from gettext import gettext as _


class MyErrorHandler(BaseErrorHandler):
    """ Models cerberus' legacy. Returns a :class:`dict`. When mangled
        through :class:`str` a pretty-formatted representation of that
        tree is returned.
    """
    messages = {
        0x00: "{0}",
        0x01: _("document is missing"),
        0x02: _("required field"),
        0x03: _("unknown field"),
        0x04: _("field '{0}' is required"),
        0x05: _("depends on these values: {constraint}"),
        0x06: _("{0} must not be present with '{field}'"),
        0x21: _("'{0}' is not a document, must be a dict"),
        0x22: _("empty values not allowed"),
        0x23: _("null value not allowed"),
        0x24: _("must be of {constraint} type"),
        0x25: _("must be of dict type"),
        0x26: _("length of list should be {constraint}, it is {0}"),
        0x27: _("min length is {constraint}"),
        0x28: _("max length is {constraint}"),
        0x41: _("value does not match regex '{constraint}'"),
        0x42: _("min value is {constraint}"),
        0x43: _("max value is {constraint}"),
        0x44: _("unallowed value {value}"),
        0x45: _("unallowed values {0}"),
        0x46: _("unallowed value {value}"),
        0x47: _("unallowed values {0}"),
        0x48: _("missing members {0}"),
        0x61: _("field '{field}' cannot be coerced: {0}"),
        0x62: _("field '{field}' cannot be renamed: {0}"),
        0x63: _("field is read-only"),
        0x64: _("default value for '{field}' cannot be set: {0}"),
        0x81: _("mapping doesn't validate subschema: {0}"),
        0x82: _("one or more sequence-items don't validate: {0}"),
        0x83: _("one or more keys of a mapping  don't validate: {0}"),
        0x84: _("one or more values in a mapping don't validate: {0}"),
        0x85: _("one or more sequence-items don't validate: {0}"),
        0x91: _("one or more definitions validate"),
        0x92: _("none or more than one rule validate"),
        0x93: _("no definitions validate"),
        0x94: _("one or more definitions don't validate"),
    }

    def __init__(self, tree=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.tree = {} if tree is None else tree

    def __call__(self, errors):
        self.clear()
        self.extend(errors)
        return self.pretty_tree

    def __str__(self):
        return pformat(self.pretty_tree)

    @property
    def pretty_tree(self):
        pretty = deepcopy(self.tree)
        for field in pretty:
            self._purge_empty_dicts(pretty[field])
        return pretty

    @encode_unicode
    def add(self, error):
        # Make sure the original error is not altered with
        # error paths specific to the handler.
        error = deepcopy(error)

        self._rewrite_error_path(error)

        if error.is_logic_error:
            self._insert_logic_error(error)
        elif error.is_group_error:
            self._insert_group_error(error)
        elif error.code in self.messages:
            self._insert_error(
                error.document_path, self._format_message(error.field, error)
            )

    def clear(self):
        self.tree = {}

    def start(self, validator):
        self.clear()

    def _format_message(self, field, error):
        return self.messages[error.code].format(
            *error.info, constraint=error.constraint, field=field, value=error.value
        )

    def _insert_error(self, path, node):
        """ Adds an error or sub-tree to :attr:tree.

        :param path: Path to the error.
        :type path: Tuple of strings and integers.
        :param node: An error message or a sub-tree.
        :type node: String or dictionary.
        """
        field = path[0]
        if len(path) == 1:
            if field in self.tree:
                subtree = self.tree[field].pop()
                self.tree[field] += [node, subtree]
            else:
                self.tree[field] = [node, {}]
        elif len(path) >= 1:
            if field not in self.tree:
                self.tree[field] = [{}]
            subtree = self.tree[field][-1]

            if subtree:
                new = self.__class__(tree=copy(subtree))
            else:
                new = self.__class__()
            new._insert_error(path[1:], node)
            subtree.update(new.tree)

    def _insert_group_error(self, error):
        for child_error in error.child_errors:
            if child_error.is_logic_error:
                self._insert_logic_error(child_error)
            elif child_error.is_group_error:
                self._insert_group_error(child_error)
            else:
                self._insert_error(
                    child_error.document_path,
                    self._format_message(child_error.field, child_error),
                )

    def _insert_logic_error(self, error):
        field = error.field
        self._insert_error(error.document_path, self._format_message(field, error))

        for definition_errors in error.definitions_errors.values():
            for child_error in definition_errors:
                if child_error.is_logic_error:
                    self._insert_logic_error(child_error)
                elif child_error.is_group_error:
                    self._insert_group_error(child_error)
                else:
                    self._insert_error(
                        child_error.document_path,
                        self._format_message(field, child_error),
                    )

    def _purge_empty_dicts(self, error_list):
        subtree = error_list[-1]
        if not error_list[-1]:
            error_list.pop()
        else:
            for key in subtree:
                self._purge_empty_dicts(subtree[key])

    def _rewrite_error_path(self, error, offset=0):
        """
        Recursively rewrites the error path to correctly represent logic errors
        """
        if error.is_logic_error:
            self._rewrite_logic_error_path(error, offset)
        elif error.is_group_error:
            self._rewrite_group_error_path(error, offset)

    def _rewrite_group_error_path(self, error, offset=0):
        child_start = len(error.document_path) - offset

        for child_error in error.child_errors:
            relative_path = child_error.document_path[child_start:]
            child_error.document_path = error.document_path + relative_path

            self._rewrite_error_path(child_error, offset)

    def _rewrite_logic_error_path(self, error, offset=0):
        child_start = len(error.document_path) - offset

        for i, definition_errors in error.definitions_errors.items():
            if not definition_errors:
                continue

            nodename = '%s definition %s' % (error.rule, i)
            path = error.document_path + (nodename,)

            for child_error in definition_errors:
                rel_path = child_error.document_path[child_start:]
                child_error.document_path = path + rel_path

                self._rewrite_error_path(child_error, offset + 1)
if __name__ == "__main__":
    schema = {
        'name': {'type': 'string', 'required': True, 'maxlength': 4, 'empty': False}
    }
    data = {"name": "javad"}

    v = Validator(schema, error_handler=MyErrorHandler)
    status = v.validate(data)
    # occurred error
    if not status:
        pprint(v.errors)`

**Comment by javadasoodeh** [comment]
I Found:
```
from pprint import pformat, pprint

from cerberus import Validator, errors
from cerberus.errors import BaseErrorHandler, encode_unicode
from copy import copy, deepcopy
from gettext import gettext as _


class MyErrorHandler(BaseErrorHandler):
    """ Models cerberus' legacy. Returns a :class:`dict`. When mangled
        through :class:`str` a pretty-formatted representation of that
        tree is returned.
    """
    messages = {
        0x00: "{0}",
        0x01: _("document is missing"),
        0x02: _("required field"),
        0x03: _("unknown field"),
        0x04: _("field '{0}' is required"),
        0x05: _("depends on these values: {constraint}"),
        0x06: _("{0} must not be present with '{field}'"),
        0x21: _("'{0}' is not a document, must be a dict"),
        0x22: _("empty values not allowed"),
        0x23: _("null value not allowed"),
        0x24: _("must be of {constraint} type"),
        0x25: _("must be of dict type"),
        0x26: _("length of list should be {constraint}, it is {0}"),
        0x27: _("min length is {constraint}"),
        0x28: _("max length is {constraint}"),
        0x41: _("value does not match regex '{constraint}'"),
        0x42: _("min value is {constraint}"),
        0x43: _("max value is {constraint}"),
        0x44: _("unallowed value {value}"),
        0x45: _("unallowed values {0}"),
        0x46: _("unallowed value {value}"),
        0x47: _("unallowed values {0}"),
        0x48: _("missing members {0}"),
        0x61: _("field '{field}' cannot be coerced: {0}"),
        0x62: _("field '{field}' cannot be renamed: {0}"),
        0x63: _("field is read-only"),
        0x64: _("default value for '{field}' cannot be set: {0}"),
        0x81: _("mapping doesn't validate subschema: {0}"),
        0x82: _("one or more sequence-items don't validate: {0}"),
        0x83: _("one or more keys of a mapping  don't validate: {0}"),
        0x84: _("one or more values in a mapping don't validate: {0}"),
        0x85: _("one or more sequence-items don't validate: {0}"),
        0x91: _("one or more definitions validate"),
        0x92: _("none or more than one rule validate"),
        0x93: _("no definitions validate"),
        0x94: _("one or more definitions don't validate"),
    }

    def __init__(self, tree=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.tree = {} if tree is None else tree

    def __call__(self, errors):
        self.clear()
        self.extend(errors)
        return self.pretty_tree

    def __str__(self):
        return pformat(self.pretty_tree)

    @property
    def pretty_tree(self):
        pretty = deepcopy(self.tree)
        for field in pretty:
            self._purge_empty_dicts(pretty[field])
        return pretty

    @encode_unicode
    def add(self, error):
        # Make sure the original error is not altered with
        # error paths specific to the handler.
        error = deepcopy(error)

        self._rewrite_error_path(error)

        if error.is_logic_error:
            self._insert_logic_error(error)
        elif error.is_group_error:
            self._insert_group_error(error)
        elif error.code in self.messages:
            self._insert_error(
                error.document_path, self._format_message(error.field, error)
            )

    def clear(self):
        self.tree = {}

    def start(self, validator):
        self.clear()

    def _format_message(self, field, error):
        return self.messages[error.code].format(
            *error.info, constraint=error.constraint, field=field, value=error.value
        )

    def _insert_error(self, path, node):
        """ Adds an error or sub-tree to :attr:tree.

        :param path: Path to the error.
        :type path: Tuple of strings and integers.
        :param node: An error message or a sub-tree.
        :type node: String or dictionary.
        """
        field = path[0]
        if len(path) == 1:
            if field in self.tree:
                subtree = self.tree[field].pop()
                self.tree[field] += [node, subtree]
            else:
                self.tree[field] = [node, {}]
        elif len(path) >= 1:
            if field not in self.tree:
                self.tree[field] = [{}]
            subtree = self.tree[field][-1]

            if subtree:
                new = self.__class__(tree=copy(subtree))
            else:
                new = self.__class__()
            new._insert_error(path[1:], node)
            subtree.update(new.tree)

    def _insert_group_error(self, error):
        for child_error in error.child_errors:
            if child_error.is_logic_error:
                self._insert_logic_error(child_error)
            elif child_error.is_group_error:
                self._insert_group_error(child_error)
            else:
                self._insert_error(
                    child_error.document_path,
                    self._format_message(child_error.field, child_error),
                )

    def _insert_logic_error(self, error):
        field = error.field
        self._insert_error(error.document_path, self._format_message(field, error))

        for definition_errors in error.definitions_errors.values():
            for child_error in definition_errors:
                if child_error.is_logic_error:
                    self._insert_logic_error(child_error)
                elif child_error.is_group_error:
                    self._insert_group_error(child_error)
                else:
                    self._insert_error(
                        child_error.document_path,
                        self._format_message(field, child_error),
                    )

    def _purge_empty_dicts(self, error_list):
        subtree = error_list[-1]
        if not error_list[-1]:
            error_list.pop()
        else:
            for key in subtree:
                self._purge_empty_dicts(subtree[key])

    def _rewrite_error_path(self, error, offset=0):
        """
        Recursively rewrites the error path to correctly represent logic errors
        """
        if error.is_logic_error:
            self._rewrite_logic_error_path(error, offset)
        elif error.is_group_error:
            self._rewrite_group_error_path(error, offset)

    def _rewrite_group_error_path(self, error, offset=0):
        child_start = len(error.document_path) - offset

        for child_error in error.child_errors:
            relative_path = child_error.document_path[child_start:]
            child_error.document_path = error.document_path + relative_path

            self._rewrite_error_path(child_error, offset)

    def _rewrite_logic_error_path(self, error, offset=0):
        child_start = len(error.document_path) - offset

        for i, definition_errors in error.definitions_errors.items():
            if not definition_errors:
                continue

            nodename = '%s definition %s' % (error.rule, i)
            path = error.document_path + (nodename,)

            for child_error in definition_errors:
                rel_path = child_error.document_path[child_start:]
                child_error.document_path = path + rel_path

                self._rewrite_error_path(child_error, offset + 1)

if __name__ == "__main__":
    schema = {
        'name': {'type': 'string', 'required': True, 'maxlength': 4, 'empty': False}
    }
    data = {"name": "javad"}

    v = Validator(schema, error_handler=MyErrorHandler)
    status = v.validate(data)
    # occurred error
    if not status:
        pprint(v.errors)
```

**Comment by funkyfuture** [comment]
i have no clue what you are aiming at by copying code into an issue. there are already issues (maybe closed ones) and maybe questions on the topic you mention in the issue title.
