### ISSUE TITLE
Running into an issue with Boolean types

### ISSUE THREAD

**Issue by aronchick** [pyeve/cerberus#535]
Used Cerberus version / latest commit: …

- [X] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [X] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

I'm importing things from yaml into python objects using the strictyaml library. An issue I'm running into is that it casts all objects into strings, and then the strings validated against the schema. So the issue I'm running into is here:

```
v = Validator()

UUID = """
run_id:
    type: uuid
    required: True
"""
a = strictyaml.load(UUID).data
# Value of a => OrderedDict([('run_id',
#                   OrderedDict([('type', 'uuid'), ('required', 'True')]))])

b = ruamel.YAML.load(UUID)
# Value of b => {'run_id': {'type': 'uuid', 'required': True}}

s.schema = b
# Output => SchemaError: {'run_id': [{'required': ['must be of boolean type']}]}

s.schema = a
# Output => True (it worked)
```

Is there a simple way to force boolean without requiring the user to add coerce/normalization to the schema?

**Comment by funkyfuture** [comment]
without using Cerberus to notmalize, that's an issue w/ `strictyaml`.

**Comment by aronchick** [comment]
It's true, strictyaml doesn't cast to a boolean, I'm just wondering if there's a way to override the base validator for boolean so that I can cast it?

**Comment by funkyfuture** [comment]
no.

(got the pun?)

as far as i understand `strictyaml` isn't a valid YaML parser. there's PyYAML that parses booleans correctly.
