### ISSUE TITLE
Need normalization AFTER validation

### ISSUE THREAD

**Issue by socketpair** [pyeve/cerberus#536]
The case: I need to have a field with IP and prefix, like `1.2.3.4/24`.

I need my system to eat both `1.2.3.4/255.255.255.0` and `1.2.3.4/24`, and the first should be normalized to the last form.

If I add coercion like `lambda value: str(ipaddress.IPv4address(value))` it will also eat strings like `1.2.3.4` (without a mask) and even integer values, which is input error for sure. Yep, I can merge validator with the coercion, but it looks awkward and weird, and I also have no way to call `error(field, message)` in this case.

I need first to validate that value is a string, that it matches specific regexp, and THEN run some normalizer like `lambda` mentioned before.

**Comment by Mirraz** [comment]
OR add new validation rule "validate_and_normalize" with callable value in which we can validate and normalize input data field.

**Comment by funkyfuture** [comment]
you're advised to use a function and not a lambda for everything, especially when a lambda is insufficient for complex logic.

when you first want to validate and then normalize, try calling the methods in that order. possibly with different schemas or use different validators.

**Comment by socketpair** [comment]
@funkyfuture could you provide (or point to) an example?

> try calling in that order
I don't understand that. Cerberus calls, not me.

**Comment by funkyfuture** [comment]
```python

validator = Validator(validation_schema)
normalizer = Validator(normalization_schema)

if validator(document):
    document = normalizer.normalized(document)
else:
    …
```
