### ISSUE TITLE
We cannot use a "validator" function for Arrays. It think it would be a great addition!

### ISSUE THREAD

**Issue by Abhisek1994Roy** [pyeve/cerberus#541]
Used Cerberus version / latest commit: …

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

----

**Comment by funkyfuture** [comment]
1) it is possible to use `validator` / `check_with` with lists.

2) please restrain from opening issues without actual content.
