### ISSUE TITLE
Error when pytest

### ISSUE THREAD

**Issue by xinjiyier** [pyeve/cerberus#542]
#### Bug report 

error when I pytest   
environment:  pytest 5.4.1  

Below is the error message :
cerberus/tests/test_zzz_validated_schema_cache.py .                                                                                                                                                  [100%]

================================================================================================== ERRORS ==================================================================================================
________________________________________________________________________________ ERROR at setup of test_overall_performance ________________________________________________________________________________
file /home/shoppingchen/work/xml-json-test/cerberus/cerberus/benchmarks/test_overall_performance.py, line 141
  def test_overall_performance(benchmark):
E       fixture 'benchmark' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, extra, metadata, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/home/shoppingchen/work/xml-json-test/cerberus/cerberus/benchmarks/test_overall_performance.py:141
======================================================================================= 394 passed, 1 error in 3.51s =======================================================================================

**Comment by funkyfuture** [comment]
it seems that you copied the Cerberus' source into your project. you can to that, but it's your responsibility to select only the proper parts of the test suite. running the benchmark requires the `pytest-benchmark` package.
