### ISSUE TITLE
use cerberus to check the clear resut data ,the cpu cost is hight  near 100%

### ISSUE THREAD

**Issue by abo123456789** [pyeve/cerberus#543]
Used Cerberus version / latest commit: …

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

 v = Validator()
        v.allow_unknown = True
        schema = schema = {
            "_id": {'type': 'string', 'empty': False, 'required': True},
            "s_id": {'type': 'string', 'empty': False, 'required': True},
            "from": {'type': 'string', 'empty': False, 'required': True},
            "from_cn": {'type': 'string', 'empty': False, 'required': True},
            "title": {'type': 'string', 'empty': False, 'required': True},
            "course_type": {'type': 'integer', 'empty': False, 'required': True, 'regex': '^(1|2)$'},
            "price": {'type': 'float', 'empty': False, 'required': True}}
       formate_data = {}
        check_result = v.validate(formate_data, schema)

----

#### Bug report / Feature request

when i run a python craw and use cerberus to check the clear resut data ,the cpu cost is hight  near 100% ,any one has some method to resolve the problem?

**Comment by funkyfuture** [comment]
please describe your issues in a meaningful manner that makes sense to others. cpu usage isn't bad per se.
