### ISSUE TITLE
default value is not set when the parent dict node is not specified

### ISSUE THREAD

**Issue by thiagocrepaldi** [pyeve/cerberus#546]
Used Cerberus version / latest commit: 1.3.2

- [N] I have the capacity to improve the docs when my problem is solved.
- [N] I have the capacity to submit a patch when a bug is identified.

- [N] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Bug report / Feature request

By specifying a schema which contains a non required dictionary in which one of the entries has a default value, after validating it, if the dict is not specified, the entry in the dict doesn't get a default value assigned.
```python

schema = {
    'dict1' : {
        'type' : 'dict',
        'required' : False,
        'schema' : {
            'key1: {
                'type' : 'integer', 'default' : 123
            }
        },
}

val = cerberus.Validator(schema)
print(val.validated({})
> {}
```

Expected behavior would be something like `{'dict1' : {'key1' : 123}}`

One ugly workaround is specifying an empty dictionary

```python
val = cerberus.Validator(schema)
print(val.validated({'dict1'})
> {'dict1' : {'key1' : 123}
```

Although it is valid to return {} in the scenario above, it is also valid to return a schema that returns all keys with default values. This is interesting to inform users about default values on an incomplete but valid schema. 

A new flag on `Validator` such as `force_default=False` could implement this new behavior

**Comment by funkyfuture** [comment]
what about

```python
schema = {
    'dict1' : {
        'type' : 'dict',
        'required' : False,
        'default_setter': dict,
        'schema' : {
            'key1: {
                'type' : 'integer', 'default' : 123
            }
        },
}
```

or?

```python
schema = {
    'dict1' : {
        'type' : 'dict',
        'required' : False,
        'default_setter': lambda _: {'type': 123},
        'schema' : {
            'key1: {
                'type' : 'integer',
            }
        },
}
```

> One ugly workaround is specifying an empty dictionary

the accompanying example seems incomplete.

> A new flag on `Validator` such as `force_default=False` could implement this new behavior

long story short: it wouldn't. it's not simple to implement with the current (normalization) architecture. and before we'd go down the road to refactor that, i'll finally say:

> ENOUGH! let's separate normalization into its own class / processing unit that is independent of validation.

**Comment by thiagocrepaldi** [comment]
> what about
> 
> ```python
> schema = {
>     'dict1' : {
>         'type' : 'dict',
>         'required' : False,
>         'default_setter': dict,
>         'schema' : {
>             'key1: {
>                 'type' : 'integer', 'default' : 123
>             }
>         },
> }
> ```
> 
> or?
> 
> ```python
> schema = {
>     'dict1' : {
>         'type' : 'dict',
>         'required' : False,
>         'default_setter': lambda _: {'type': 123},
>         'schema' : {
>             'key1: {
>                 'type' : 'integer',
>             }
>         },
> }
> ```
Thank you for the reply. `'default_setter': dict,` only works for my original example (single optional dict), but it fails for multiple dicts:
```python
import cerberus

schema = {
    'dict1' : {
        'type' : 'dict',
        'default_setter' : dict,
        'required' : False,
        'schema' : {
            'key1': {
                'type' : 'integer', 'default' : 123
            }
        },
    },
    'dict2' : {
        'type' : 'dict',
        'default_setter': dict,
        'required' : False,
        'schema' : {
            'key2': {
                'type' : 'integer', 'default' : 456
            }
        },
    }
}

val = cerberus.Validator(schema)
print(val.validated({}))
> None
```
The second solution, on the other hand, works for multiple dicts too! THANK YOU!
```python
import cerberus

schema = {
    'dict1' : {
        'type' : 'dict',
        'default_setter': lambda _: {},
        'required' : False,
        'schema' : {
            'key1': {
                'type' : 'integer', 'default' : 123
            }
        },
    },
    'dict2' : {
        'type' : 'dict',
        'default_setter': lambda _: {},
        'required' : False,
        'schema' : {
            'key2': {
                'type' : 'integer', 'default' : 456
            }
        },
    }
}

val = cerberus.Validator(schema)
print(val.validated({}))
> {'dict1': {'key1': 123}, 'dict2': {'key2': 456}}
```

Would it make sense to use `'default_setter': lambda _: {},` by default on the validator on cerberus?

> 
> > One ugly workaround is specifying an empty dictionary
> 
> the accompanying example seems incomplete.
> 
> > A new flag on `Validator` such as `force_default=False` could implement this new behavior
> 
> long story short: it wouldn't. it's not simple to implement with the current (normalization) architecture. and before we'd go down the road to refactor that, i'll finally say:
> 
> > ENOUGH! let's separate normalization into its own class / processing unit that is independent of validation.
Is this an advice for how I am using cerberus or a design discussion on cerberus? :)

**Comment by funkyfuture** [comment]
> Would it make sense to use `'default_setter': lambda _: {}`, by default on the validator on cerberus?

i don't think that Cerberus should try to anticipate what the user wants to with it since all use-cases are different.

> Is this an advice for how I am using cerberus or a design discussion on cerberus? :)

rather the latter, but actually no.
