### ISSUE TITLE
unknown rule: propertyschema

### ISSUE THREAD

**Issue by sakitA** [pyeve/cerberus#548]
used version: 1.3.2

there is no `propertyschema` rule instead has `keyschema`. I don't know this a bug or documentation error

**Comment by funkyfuture** [comment]
i don't understand what your concern is. maybe this helps: https://github.com/pyeve/cerberus/blob/master/UPGRADING.rst#keyschema--valueschema

**Comment by sakitA** [comment]
@funkyfuture thank you for your help. The [documentation](https://cerberus-sanhe.readthedocs.io/usage.html#propertyschema) said that there is a `propertyschema` rule.  According to the link on your comment, this ruled renamed to `keyschema`

**Comment by funkyfuture** [comment]
that is actually not an official, and actually outdated, deployment of our docs. @MacHu-GWU, would you be so kind to take it down or clearly mark that it is not the actual Cerberus docs? we have some irritated users that are referring to yours from time to time.

**Comment by nicolaiarocci** [comment]
this is your friendly reminder that the official Cerberus documentation is available at https://docs.python-cerberus.org/en/stable/

**Comment by sakitA** [comment]
@nicolaiarocci thank you very much. I did not know that I used outdated documentation.
