### ISSUE TITLE
Custom error handling/Error readability support with Cerberus

### ISSUE THREAD

**Issue by Chetana27** [pyeve/cerberus#549]
Used Cerberus version / latest commit: … **1.3.2**

- [x] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract
Error readability/ Human readability needs to be enhanced for better debuggability in Cerberus
----

#### Bug report / Feature request
We are coming up with a Yaml validation tool. Even with custom error messages, the entire field gets printed which is not required/easy to debug the issues. Is there any way in which this can be achieved? How do we add simple error handling messages without any additional fields/arguments? If the feature is already present/has a workaround, kindly provide a couple of examples.

The problem arises when the input is a complex nested dictionary and we would not want the entire dict to be printed in the error msg.

Eg: 'abc_variables': ['none or more than one rule validate',
                    {'oneof definition 0': ['must be of string type'],
                     'oneof definition 1': [{'ab - addpath_policy': ['value '
                                                                     'does not '
                                                                     'match '
                                                                     'regex '
                                                                     "'[a-zA-Z0-9-_]+'"]}],
                     'oneof definition 2': ['must be of list type']}]}

error(field, " some msg ") <<< can this be modified to just present the human readable errors (custom messages without the fields - similar to an exception)

**Comment by funkyfuture** [comment]
you can implement a custom representation of errors. see https://docs.python-cerberus.org/en/stable/errors.html
