### ISSUE TITLE
Add const validator

### ISSUE THREAD

**Issue by boulderwebdev** [pyeve/cerberus#550]
Used Cerberus version / latest commit: …

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [x] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

Const values were added to the [JSONSchema draft in version 6](https://json-schema.org/understanding-json-schema/reference/generic.html#constant-values) and I think this feature should be included with Cerberus. For example, if you have a schema representing a job, and a field called `job_type`, which is an enum of values, depending on the value, I may want to validate against a specific schema. Then, because this is the case, I want each schema to have a `const` based upon which `job_type` is present.

----

Here's an example implementation

```python
from cerberus import Validator

class ConstValidator(Validator):

    def _validate_const(self, const, field, value):
        """The rule's arguments are validated against this schema:
        {'type': (
            'boolean', 'binary', 'date', 'datetime', 'float',
            'integer', 'number', 'string'
        )}"""
        if const != value:
            self._error(field, "Must be equal to {}".format(const))

if __name__ == "__main__":
    v = ConstValidator({
        "job_type": {
            "type": "string",
            "const": "update"
        }
    })

    x = {"job_type": "update"}
    print(x)
    print(v.validate(x))
    print(v.errors, "\n")

    x = {"job_type": "asdf"}
    print(x)
    print(v.validate(x))
    print(v.errors, "\n")

```

**Comment by funkyfuture** [comment]
do you mean like the `allowed` rule, but for one value only?

**Comment by boulderwebdev** [comment]
Yes, that's correct.

**Comment by funkyfuture** [comment]
are you okay with using the `allowed` rule and assigning it a constraint with one value?

**Comment by boulderwebdev** [comment]
If that case is taken, there should be an addition to the documentation so if someone searches "const" or "constant" the allowed section comes up with the suggested solution as a subsection of the [allowed section](https://docs.python-cerberus.org/en/stable/validation-rules.html#allowed).

**Comment by funkyfuture** [comment]
i don't think we should add possible alternate names of rules to the docs.
