### ISSUE TITLE
Feature Request: Allow rename to go deep

### ISSUE THREAD

**Issue by jeking3** [pyeve/cerberus#552]
Used Cerberus version / latest commit: …

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

I would like to be able to rename a property into a stanza, for example:

```
username: foo
password: bar
```

normalize to:

```
configure:
  admin:
    username: foo
    password: bar
```

without requiring custom code.  Right now rename is limited to simple renaming in the same stanza.

----

#### Bug report / Feature request

The ability to rename "deeply" would be useful, for example:

```
  {"username": {"rename": "&.configure.admin.username"},
   "password": {"rename": "&.configure.admin.password"}}
```

or something similar.

**Comment by funkyfuture** [comment]
we don't intend to add futher features to Cerberus.
