### ISSUE TITLE
'dependencies' incorrectly validated  by not-required field

### ISSUE THREAD

**Issue by thiagocrepaldi** [pyeve/cerberus#553]
```python
from cerberus import Validator
schema = {
        'feature': {
        'type': 'dict',
        'default_setter': lambda _: {},
        'required': False,
        'schema': {
            'enabled': {
                'type': 'boolean',
                'required': False,
                'default': False
            },
            'subfeature': {
                'required': False,
                'type': 'integer',
                'nullable': True,
                'default': None,
                'dependencies': {'^feature.enabled' : True}
            }
        }
    },
}

v = Validator()
v.validate({'feature' : {'enabled' : True}}, schema) # expected True, actual True
v.validate({'feature' : {'enabled' : False}}, schema)  # expected True, actual False
v.validate({'feature' : {'enabled' : False, 'subfeature' : None}}, schema)  # expected True, actual False
v.validate({'feature' : {'enabled' : True, 'subfeature' : 3}}, schema)  # expected True, actual True
v.validate({'feature' : {'enabled' : False, 'subfeature' : 3}}, schema)  # expected True, actual False
```

Used Cerberus version / latest commit:1.3.2 (from pip)

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

I have a schema in which the main dict named 'feature' is optional and has a optional boolean field named "enabled".
This dict has a nested dict named 'subfeature' which is also optional and depends on the parent dict's 'enabled' field to be 'True' as a validation. Meaning the subfeature cant be set if the feature is not.

----

#### Bug report / Feature request

The problem is that when the main 'feature.enabled':False occurs, the nested dict which is not being set complains the feature.enabled is not True. This shouldnt happen because the nested dict is optional and is not being assigned, so it shouldnt validate. If the subfeature was required, than this behavior would make sense, but for optional fields, this is unexpected.

**Comment by funkyfuture** [comment]
i haven't looked closely at this. does it also behave unexpectedly when you address the enabled field relatively?

**Comment by thiagocrepaldi** [comment]
> i haven't looked closely at this. does it also behave unexpectedly when you address the enabled field relatively?

Hello @funkyfuture changing `'dependencies': {'^feature.enabled' : True}` to `'dependencies': {'enabled' : True}` makes no difference. I only used the full level to get better error messages

**Comment by funkyfuture** [comment]
i can reproduce the bug and i stripped the test case down so far that the `required` rule plays no role (except the default mentioned in the summary).

```python
@mark.parametrize(
    "document",
    [
        {"enabled": True},
        {"enabled": False},
        {'enabled': False, 'subfeature': None},
        {'enabled': True, 'subfeature': 3},
        {'enabled': False, 'subfeature': 3},
    ],
)
def test_issue_553(document):
    # https://github.com/pyeve/cerberus/issues/553
    schema = {
        "enabled": {},
        "subfeature": {
            "nullable": True,
            # removing this eliminates one error:
            "default": None,
            "dependencies": {"enabled": True},
        },
    }
    assert_success(document, schema)
```

**Comment by funkyfuture** [comment]
well, i figured it's actually not a bug. e.g,. your second case sets a default which results in the document where the `subfeature` field is present. hence that field will be validated and it expects `enabled` to be `True`. the other cases are even more obvious in this regard. the value of a field doesn't matter when its dependencies are verified. for more sophisticated logics like this, there are custom rules.

**Comment by thiagocrepaldi** [comment]
Hi @funkyfuture, thanks for looking into this. I didn't understand your last comment, though. COuld you elaborate a little more on why this is not a bug? Seems very subtle...

**Comment by funkyfuture** [comment]
it isn't a bug because it works as intended. my understanding is that the `dependencies` rule wouldn't be evaluated when the `subfeature` field has the value `None`. could you elaborate why you would expect the failing results rather to pass?

these cases are usually addressed with the `oneof` rule, for the `feature` rule in your case.

**Comment by thiagocrepaldi** [comment]
> it isn't a bug because it works as intended. my understanding is that the `dependencies` rule wouldn't be evaluated when the `subfeature` field has the value `None`. could you elaborate why you would expect the failing results rather to pass?
> 
> these cases are usually addressed with the `oneof` rule, for the `feature` rule in your case.

This looks a different scenario. The reported one is 2 nested dicts and the inner (subfeature) dict depends on an attribute 'enabled' of the outer dict (feature). The inner dict can't be None

**Comment by funkyfuture** [comment]
i have looked around on SO and didn't find a well-fitting question/answer. i also really can't guess where your expectations diverge from the implementations.

let me try to point one thing out again: as you define a dfault for `subfeature`, the field will always be present in the document. the `depenedencies` rule defined on that field always expects the `enabled` field to be `True`. hence all documents where it holds `False` are evaluated as invalid.
