### ISSUE TITLE
how to validate Nested JSON

### ISSUE THREAD

**Issue by takeMeFlyToAir** [pyeve/cerberus#561]
for example, my json object is 
{
    "student":{
        "basic":{
            "sex":"male",
            "address":{
                "province":"beijing",
                "city":"beijing"
            }
        },
        "other":{
            "happy":"footer"
        }
    }
}
now I want only to validate "address" attribute, and I want to use whole json object, so How to write my schema？

**Comment by funkyfuture** [comment]
i propose you read the docs and/or look around on StackOverflow. they also have guides how questions can be asked so the asked people can now what the question is actually about.
