### ISSUE TITLE
PyYAML Schema Serialisation - Coerce functions are not dereferenced

### ISSUE THREAD

**Issue by rendorHaevyn** [pyeve/cerberus#563]
Used Cerberus version / latest commit: version 1.3.2

- [x] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.
- [x] My question does not concern a practical use-case that I can't figure out
      to solve.  (this is an oddly worded sentence)

----

##### WHAT:
When pyYAML is used to serialise for creation of the schema, coerce variables are escaped with single quotes, and are not recognised by the validator as functions.  This also occurs with built-ins (ie: `str`, `int`).

##### NEED:
Cerberus Validator needs to interpret all strings declared under the coerce directive as functions, without the user being required to explicitly update the schema.

----

#### Bug report / Feature request

1. Set up 
```python
import yaml
import cerberus

v = cerberus.Validator()
```

2. Create coerce function
```python
to_upper = lambda v: v.upper()
```

3. Create schema and document
```python
# The coerce function below will be escaped by quotes and not interpreted
schema_text = '''
claim:
    type: dict
    schema:
        testInd:
            type: string
        city:
            type: string
            coerce: to_upper
'''
schema = yaml.load(schema_text, Loader=yaml.FullLoader)
print(schema)

# Explicitly typing the coerce function works
schema_func = {'claim': {'type': 'dict', 'schema': {'testInd': {'type': 'string'}, 'city': {'type': 'string', 'coerce': to_upper}}}}
print(schema_func)

doc = {'claim':{'testInd':'5','city':'anicecity'}}
```

Output:
>>> print(schema)
{'claim': {'type': 'dict', 'schema': {'testIndicator': {'type': 'string'}, 'city': {'type': 'string', 'coerce': 'to_upper'}}}}
>>> print(schema_func)
{'claim': {'type': 'dict', 'schema': {'testInidcator': {'type': 'string'}, 'city': {'type': 'string', 'coerce': <function <lambda> at 0x7feaf0a31950>}}}}

4. Validating will fail
```python
v.validate(doc,schema_func)
v.validate(doc,schema)
```

Output:
>>> v.validate(doc,schema_func)
True
>>> v.validate(doc,schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/csmcp/venv-ubuntu/lib/python3.6/site-packages/cerberus/validator.py", line 988, in validate
    self.__init_processing(document, schema)
  File "/mnt/c/Users/csmcp/venv-ubuntu/lib/python3.6/site-packages/cerberus/validator.py", line 601, in __init_processing
    self.schema = DefinitionSchema(self, schema)
  File "/mnt/c/Users/csmcp/venv-ubuntu/lib/python3.6/site-packages/cerberus/schema.py", line 82, in __init__
    self.validate(schema)
  File "/mnt/c/Users/csmcp/venv-ubuntu/lib/python3.6/site-packages/cerberus/schema.py", line 262, in validate
    self._validate(schema)
  File "/mnt/c/Users/csmcp/venv-ubuntu/lib/python3.6/site-packages/cerberus/schema.py", line 278, in _validate
    raise SchemaError(self.schema_validator.errors)
cerberus.schema.SchemaError: {'claim': [{'schema': ['no definitions validate', {'anyof definition 0': [{'city': [{'coerce': ['none or more than one rule validate', {'oneof definition 0': ['must be of callable type'], 'oneof definition 1': ['must be of list type'], 'oneof definition 2': ['unallowed value to_upper']}]}]}], 'anyof definition 1': [{'city': ['unknown rule'], 'testInd': ['unknown rule']}]}]}]}

5. Explicitly adding in the function works
```python
schema['claim']['schema']['city'].update({'coerce':to_upper})
v.validate(doc,schema)
```

Output:
>>> schema['claim']['schema']['city'].update({'coerce':to_upper})
>>> v.validate(doc,schema)
True

**Comment by funkyfuture** [comment]
that stems from the fact that the callable and the string are completely different things. you want to have a look at the [extension chapter](https://docs.python-cerberus.org/en/stable/customize.html) regarding referenced coercers in customized validators.
