### ISSUE TITLE
_validate_type_<new type> doesn't work when rewritten with TypeDefinition

### ISSUE THREAD

**Issue by darenr** [pyeve/cerberus#573]
this works, but throws warning:

```python
class MyOperatorValidator(cerberus.Validator):
    def _validate_type_ocid(self, value):
        if re.match("^ocid[123][.].*$", value):
            return True
```
But this just ignores the type definition

```python

class Ocid:
    def __init__(self, v):
        print(v) # debug - never called

v = cerberus.Validator(schema)
v.types_mapping['ocid'] = cerberus.TypeDefinition('ocid', (Ocid,), ())
```

only ever get `'Unsupported types: ocid'` no matter what I do. The docs could benefit from an example showing the old `_validate_type_<type>` method with a simple example. Using `decimal` doesn't help since that doesn't show the actual type validation.

**Comment by funkyfuture** [comment]
is the value that you validate an instance of `Ocid`? the validation is not supposed to initialize values, hence that `__init__` method won't be called by Cerberus. for validating strings against a regex pattern, there is the `regex` rule.

for further assistance, please browse /or ask on StackOverflow. if this service not feasible for you, please ping back here with sufficient documentation about your doings.
