### ISSUE TITLE
Missing `py.typed` marker for mypy typechecks

### ISSUE THREAD

**Issue by dhuckins** [pyeve/cerberus#581]
Used Cerberus version / latest commit:
- version: 1.3.4

- [ X ] I have the capacity to improve the docs when my problem is solved.
- [ X ] I have the capacity to submit a patch when a bug is identified.

----

#### Bug report / Feature request

when trying to use a static type checker (in this case mypy) `cerberus` is not detected as installed because it is missing the `py.typed` file (see [PEP 561](https://www.python.org/dev/peps/pep-0561/))

eg:
```sh
mypy my_pkg
...
my_pkg/validation.py:6: error: Skipping analyzing "cerberus": module is installed, but missing library stubs or py.typed marker
```

Can we assume that cerberus is a typed?

**Comment by dhuckins** [comment]
following up

should I just make a pull request?

**Comment by funkyfuture** [comment]
ciao, sorry, is somehow missed the initial post.

the 1.3 branch isn't annotated at all, so afaik you have to ignore it when you type check your code.

**Comment by dhuckins** [comment]
not too worried about older versions
can it be added to the current branch? (looks like v2)

**Comment by funkyfuture** [comment]
yes, sure.

please be aware that the current code in the `master` branch is anything but near the aim of a version 2 release.

**Comment by dhuckins** [comment]
fair enough, thanks for the heads up!

is there another v1 release coming before v2? or should I just make a PR to the default branch (and wait patiently for it to be rolled out in v2)

**Comment by funkyfuture** [comment]
i'm closing this as we don't intend to work on a new major relase.

i would accept well-crafted annotations for the 1.3-series, but i assume this is impossible given the many dynamic uses of Python and unknown input types.
