### ISSUE TITLE
Add a Normalizer for data normalization in future

### ISSUE THREAD

**Issue by liqb** [pyeve/cerberus#586]
####  Feature request

Currently Validator is designed for both data validation and normalization. This introduce some logic difficulties in schema writing. It's could be better if cerberus could add a Normalizer and move normalization related functions in Validator to Normalizer.  With Normalizer, people write a validation schema and create a Validator for data validation, write a normalization schema and create a Normalizer for data normalization. The life could be much easier! So I suggest to add a Normalizer in cerberus in the future.

**Comment by funkyfuture** [comment]
indeed it can well make sense to separate these concerns in an application. without further knowledge of you actual problem,

1) have you attempted to formulate two distinct schemas?

2) you could try to derive a normalizer and a validator from the `Validator` class where the complementing methods are overridden as effectively no-ops.

**Comment by liqb** [comment]
> 

1. yes, I made two schemas in my app, one for data validation and the another one for normalization.
2. This is what I did in my app. 

I just feels it's hard to understand that Normalizer is made from Validator. In my opinion, add a Normalizer to cerberus and add more dict mutate methods could make cerberus better with respect to data normalization.

**Comment by funkyfuture** [comment]
as we don't intend further API changes, i'm closing this issue.
