### ISSUE TITLE
How to use noneof ?

### ISSUE THREAD

**Issue by devlounge** [pyeve/cerberus#587]
Used Cerberus version / latest commit: 1.3.2

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

I have a field of type string and just want to not allow a list of values. I am trying to make it work since 2 days but no luck

example:

    schema:
      name:
        type: string
        required: True
        noneof_allowed:
        - foo
        - bar

----

#### Bug report / Feature request

How to simply implement a "disallow list" for a string field?

**Comment by funkyfuture** [comment]
ciao, i guess you're looking for the `forbidden` rule.
