### ISSUE TITLE
Use of __double_leading_underscore preventing extending

### ISSUE THREAD

**Issue by dkarp0** [pyeve/cerberus#588]
Used Cerberus version / latest commit: 1.3.4

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [x] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

To allow extending some core features of cerberus, __double_leading_underscore methods should be avoided if possible. Currently there are many e.g.:
```
__normalize_sequence_per_items
__normalize_containers
__normalize_mapping
```
And these call each other, meaning to replace some functionality of __normalize_sequence_per_items, you have to replace the `normalized` and `validate` functions that begin the call chain.

In my case, I'd like to extend `__normalize_sequence_per_items` to handle the `if len(rules) != len(values):` case for my specific validator.

----

#### Bug report / Feature request

Use _single_leading_underscore to allow for extending in child classes. I understand that __ was likely used to allow cerberus versions to change this underlying behavior without worrying about breaking people's implementations, but it severely limits how cerberus can be extended in its current state.

I propose switching some higher level method to _single_underscore and keeping them consistent between releases while leaving lower level methods as __double_underscore. In the above example, perhaps:
```
__normalize_sequence_per_items
_normalize_containers
_normalize_mapping
```

**Comment by funkyfuture** [comment]
we don't intend further API changes, so i'm clodsing this issue.
