### ISSUE TITLE
Unexpected normalization behavior with anyof_schema

### ISSUE THREAD

**Issue by gtarabat** [pyeve/cerberus#591]
Used Cerberus version / latest commit:  1.3.4

- [X] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [X] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

I want to normalize a dictionary inside a dictionary with default values. If I validate against a single schema I get the expected normalized dictionary. When I validate against two schemas with `anyof`, the behaviour changes.

----

#### Bug report

The following code validates the dictionary `{'a_dict': {}}` with the schema `A` and the schema any of `A` or `B`. The problem is that in the second case the dictionary is not being normalized as expected.

Running the code:

```
from cerberus import Validator


A = {'key': {'type': 'string', 'required': False, 'default': 'X', }}
B = {'key': {'type': 'integer', 'required': False, 'default': 1, }}

v1 = Validator({
    'a_dict': {
        'type': 'dict',
        'schema': A,
    },
})

v2 = Validator({
    'a_dict': {
        'type': 'dict',
        'anyof_schema': [A, B]
    },
})

x = {'a_dict': {}}

print(v1.validated(x))
print(v2.validated(x))
```

the result is 

```
{'a_dict': {'key': 'X'}}
{'a_dict': {}}
```

I would expect the result to be 
```
{'a_dict': {'key': 'X'}}
{'a_dict': {'key': 'X'}}
```

I am using Python 3.9 and Cerberus 1.3.4

**Comment by funkyfuture** [comment]
as noted in the docs, normalization roles can't be used within `*of`-rules.
