### ISSUE TITLE
Bug with rules_set_registry() for rule with type dict and included schema

### ISSUE THREAD

**Issue by kuza** [pyeve/cerberus#599]
Used Cerberus version / latest commit: 1.3.4
Python 3.11.3

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [x] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

I want to use earlier registered a rule with type `dict` and included `schema=`.

----

#### Bug report 
Running the code:
```python
import cerberus
cerberus.rules_set_registry.add('addr', {'type': 'dict', 'schema': {'address': {'type': 'string'}, 'city': {'type': 'string', 'required': True}}})
schema = {'a_dict': 'addr'}
document = {'a_dict': {'address': 'my address', 'city': 'my town'}}
cerberus.Validator().validate(document, schema)
```
the result is:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib64/python3.11/site-packages/cerberus/validator.py", line 1050, in validate
    self.__validate_definitions(definitions, field)
  File ".../lib64/python3.11/site-packages/cerberus/validator.py", line 1120, in __validate_definitions
    result = validate_rule(rule)
             ^^^^^^^^^^^^^^^^^^^
  File ".../lib64/python3.11/site-packages/cerberus/validator.py", line 1095, in validate_rule
    return validator(definitions.get(rule, None), field, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib64/python3.11/site-packages/cerberus/validator.py", line 1498, in _validate_schema
    self.__validate_schema_mapping(field, schema, value)
  File ".../lib64/python3.11/site-packages/cerberus/validator.py", line 1503, in __validate_schema_mapping
    allow_unknown = self.schema[field].get('allow_unknown', self.allow_unknown)
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by Pixel-Minions** [comment]
Hi, I see you are asking some questions and I can't see activity from he original creators. This project is great.

I am wondering if this project is still being maintained or valid for new versions of Python like 3.10 and 3.11.

**Comment by kuza** [comment]
> Hi, I see you are asking some questions and I can't see activity from he original creators. This project is great.
> 
> I am wondering if this project is still being maintained or valid for new versions of Python like 3.10 and 3.11.

Hi,
I also didn't see activity, but it's first bug with I detect in this project for 5 years :) so I decided to try to post it.
I use this project with Python 3.11 and do not see any additional problems.

**Comment by kuza** [comment]
@funkyfuture Thank you very much!
