### ISSUE TITLE
Address DeprecationWarning errors to fix installation warning

### ISSUE THREAD

**Issue by muhammad-mustaqeem** [pyeve/cerberus#600]
Package Installation generates a lot of deprecation warnings, crowding the shell unnecessarily:

`
.venv/lib/python3.8/site-packages/cerberus/errors.py:156
  /worker/code/.venv/lib/python3.8/site-packages/cerberus/errors.py:156: DeprecationWarning: invalid escape sequence \*
    """

.venv/lib/python3.8/site-packages/cerberus/errors.py:184
  /worker/code/.venv/lib/python3.8/site-packages/cerberus/errors.py:184: DeprecationWarning: invalid escape sequence \*
`

**Comment by funkyfuture** [comment]
we'd need more a more specific description. mind that Python allows you to silence particular warnings.

the escapings are necessary to properly render the documentation.
