### ISSUE TITLE
pyproject.toml does not specify requires-python

### ISSUE THREAD

**Issue by AustinShalit** [pyeve/cerberus#606]
Hi folks,

`cerberus==1.3.5` is being published as compatible with Python 2.7 (ignore error below, just using this command to show compatible versions):

```
~ [ pip install --python-version 27 --no-deps --target test-pkg cerberus==missing                                                            ] 9:12 AM
ERROR: Could not find a version that satisfies the requirement cerberus==missing (from versions: 0.0.1, 0.0.2, 0.0.3, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5, 0.6, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9, 0.9.1, 0.9.2, 1.0.1, 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5.dev0, 1.3.5)
```

but some testing is yielding errors.

Can we please add a `requires-python = ">PYTHON.VERSION.HERE"` to the pyproject.toml to protect against this and yank 1.3.5 from PyPI?

**Comment by lforschler** [comment]
I'm also running into issues with this on a python 2.7 environment. Following.

**Comment by funkyfuture** [comment]
this has been dine w/ 16334e58a53ae84169e61a2016228a6f1d20a1fa and if it helps you to stop using Python2, happy holidays!
