### ISSUE TITLE
anyof does not respect required: False

### ISSUE THREAD

**Issue by dkbarn** [pyeve/cerberus#610]
I am unable to define a rule for a key which can be a dict or a list, or not present at all (required: False). This is on a validator where require_all=True (which is important to keep because the vast majority of the keys are required, so it makes sense to only include "required: False" for those that aren't).

Example:
```code: python
from cerberus import Validator

schema = {
    "foo": {
        "anyof": [
            {"type": "dict", "required": False},
            {"type": "list", "required": False},
        ]
    }
}

validator = Validator(schema, require_all=True, allow_unknown=False)
if not validator.validate({}):
    print(validator.errors)
```
This prints out the error: `{'foo': ['required field']}`

**Comment by funkyfuture** [comment]
define the unrequiement one level above! if that is really the complete schema, just define multiple allowed types, `anyof` is way slower. this is not a support forum, i'm just in an indifferent mood.

**Comment by dkbarn** [comment]
That isn't the complete schema, I was just simplifying to demonstrate the problem. I need to define additional constraints that are specific to the dict/list type, which is why I'm not using "anyof_type".

```code:python
from cerberus import Validator

schema = {
    "foo": {
        "anyof": [
            {"type": "dict", "required": False, "schema": {"bar": {"type": "string"}}},
            {"type": "list", "required": False, "maxlength": 0},
        ]
    }
}

validator = Validator(schema, require_all=True, allow_unknown=False)
if not validator.validate({}):
    print(validator.errors)
```

This is a legitimate bug, not user error, so I would encourage you to reconsider your decision to close this ticket. Maybe wait until you're in a more considerate and patient mood.

**Comment by funkyfuture** [comment]
> define the unrequiement one level above!

> Maybe wait until you're in a more considerate and patient mood.

it's a'ight. iirc the issue template clearly states that this issue tracker isn't the place for usage questions. i verified, it yells it out. :shrug:

**Comment by dkbarn** [comment]
Yes I did read the issue template before submitting this issue. I am reporting a bug, not asking a usage question. My previous example clearly demonstrates that this is a bug, in that cerberus has no ability to support the schema that I've defined.
