### ISSUE TITLE
Can't use 'oneof' for a list of complex elements

### ISSUE THREAD

**Issue by McRussian** [pyeve/cerberus#616]
I have a list of values, the values can be of two different kinds. I have schemas for both types, and these schemas check for correctness. If the list contains values of only one type, then everything is fine, I can create a circuit that checks the correctness of such a list. But if I want to use objects of different types in one list, it doesn’t work.
For example, there are two schemes
```
SCHEMA_1 = {
        'name': {
            'type': 'string',
        },
        'value': {
            'type': 'integer',
            'min': 1,
            'max': 100,
        },
    }

SCHEMA_2 = {
        'name': {
            'type': 'string',
        },
        'value': {
            'type': 'string',
        },
    }

SCHEMA_LIST = {
        'value': {
        'type': 'list',
        'schema':  {
            'type': 'dict',
            'schema': SCHEMA_1,
        }
    }
}

SCHEMA_LIST2 = {
        'value': {
        'type': 'list',
        'schema':  {
            'type': 'dict',
            'schema':  SCHEMA_2,
        }
    }
}

print(v.validate({'value': [{'name': 'rr', 'value': 1}, {'name': 'dfdf', 'value': 3}]}, SCHEMA_LIST))
print(v.validate({'value': [{'name': 'rr', 'value': '1'}, {'name': 'dfdf', 'value': '3'}]}, SCHEMA_LIST2))
```
but if I try to write a circuit that needs to have different values for the elements of a list,

```
SCHEMA_COMMON = {
    'value': {
        'type': 'list',
        "schema" : {
            'type': 'dict',
            'schema': {
                'oneof': [SCHEMA_1, SCHEMA_2],
            }
        }
    }
}

print(v.validate({'value': [{'name': 'rr', 'value': 1}, {'name': 'dfdf', 'value': '3'}]}, SCHEMA_COMMON))
```
then various validation errors occur.

If you use variables of scalar types (int, string, etc.) as list elements, then everything works fine.

Is this a mistake, or am I drawing up the general diagram incorrectly?

**Comment by funkyfuture** [comment]
> am I drawing up the general diagram incorrectly?

i haven't looked closely, but that seems be the case. `oneof` is a *rule* to hold other rules, not a container to hold different *constraints*. see also [this](https://docs.python-cerberus.org/validation-rules.html#of-rules-typesaver).
